--CREAZIONE TABELLA PATOLOGIE 
CREATE TABLE PATOLOGIE(
	CODICE INTEGER REFERENCES PATINTERVENTI(IDPATOLOGIA),
	NOME VARCHAR(20),
	GRAVITA TINYINT,
	PRIMARY KEY(CODICE)
);

--CREAZIONE TABELLA PATOLOGIEINTERVENTI (RELAZIONE N A N TRA INTERVENTI E PATOLOGIE)
CREATE TABLE PATINTERVENTI (
  IDPATINTERVENTO INTEGER PRIMARY KEY AUTO_INCREMENT,
  IDINTERVENTO INTEGER,
  IDPATOLOGIA INTEGER, 
  FOREIGN KEY (IDINTERVENTO) REFERENCES INTERVENTI(ID) ON DELETE CASCADE,
  FOREIGN KEY (IDPATOLOGIA) REFERENCES PATOLOGIE(CODICE) ON DELETE CASCADE
);