/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adisys.server.boundary;

import adisys.server.strumenti.VariableTableModel;
import business.infermiere.InfermiereTO;
import business.intervento.InterventoTO;
import messaggistica.MainException;
import integration.dao.InfermiereMySqlDAO;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import presentation.FrontController;
import presentation.RequestManager;
import adisys.server.strumenti.Record;
import messaggistica.GMessage;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Gianmarco Divittorio
 * @author Nicola Gazzilli
 */
public class DialogoEsportazione extends javax.swing.JDialog implements Boundary {

    private static DialogoEsportazione window;
    private static ResourceBundle exportDialog = ResourceBundle.getBundle("adisys/server/property/DialogoEsportazione");
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JTable nursesTable;
    
    // End of variables declaration 
    
    public static void setResourceBundle(String path, Locale local){
    	exportDialog = ResourceBundle.getBundle(path, local);
    }
    
    private FrontController fController;
    
    /**
     * Creates new form DialogoEsportazione
     */
    
    public DialogoEsportazione(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DialogoEsportazione() {

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nursesTable = new javax.swing.JTable();
        exportButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(exportDialog.getString("ESPORTAZIONE PIANIFICAZIONE INFERMIERE")); // NOI18N
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        nursesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(nursesTable);

        exportButton.setText(exportDialog.getString("ESPORTA")); // NOI18N
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	exportActionPerformedbutton(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/decorazioniFinestre/Esportazione.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/decorazioniFinestre/footerEsportazione.png"))); // NOI18N

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/home.png"))); // NOI18N
        homeButton.setText(exportDialog.getString("HOME")); // NOI18N
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	homeActionPerformedButton(evt);
            }
        });

        quitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/arresta.png"))); // NOI18N
        quitButton.setText(exportDialog.getString("ABBANDONA ADISYS")); // NOI18N
        quitButton.setToolTipText(exportDialog.getString("ESCI DA ADISYS")); // NOI18N
        quitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	quitActionPerformedButton(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>                        

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        try {
        	updateTable();
        } catch (MainException ex) {
            Logger.getLogger(DialogoEsportazione.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                    

    private void exportActionPerformedbutton(java.awt.event.ActionEvent evt) {                                                
        //Controllo selezione valida
        if(nursesTable.getColumnCount() == 1)
            return;
        if (nursesTable.getSelectedRow()!=-1 ){
            //Selezione valida
            //Ricerca colonna id
            int columnID = nursesTable.getColumnModel().getColumnIndex(InfermiereMySqlDAO.NOME_COLONNA_ID);
            
            //Identificazione riga selezionata
            int selectedRow = nursesTable.getSelectedRow();
            
            //Recupero ID dell'infermiere
            int nurseID = Integer.valueOf(nursesTable.getValueAt(selectedRow, columnID).toString() );
            
            fController = RequestManager.getFCInstance();
            InfermiereTO to = new InfermiereTO();
            to.setID(nurseID);
            ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
            params.add(new Record<String, Object>("business.infermiere.InfermiereTO", to));
            try {
                boolean ok = (boolean) fController.processRequest("infermiereEsistente", params);
                if(ok){
                    //Recupero informazioni sugli interventi
                    ArrayList<InterventoTO> interventionsList = (ArrayList<InterventoTO>) 
                    		fController.processRequest("visualizzaListaInterventiInfermiere", params);
                    if(interventionsList.size() == 0)
                        GMessage.message_error(exportDialog.getString("L'INFERMIERE NON HA INTERVENTI"));
                    else {
                        params.add(new Record<String,Object>("java.util.ArrayList", interventionsList));
                        String fileName = (String) fController.processRequest("esportaPianificazione", params);
                        if(fileName !=null){
                            GMessage.information(fileName);
                        } else 
                            GMessage.message_error(exportDialog.getString(
                                    "Errore nell'esportazione: controllare il formato del file XML e riprovare"));
                    }
                } else {
                    GMessage.message_error(exportDialog.getString("IMPOSSIBILE ESPORTARE: NESSUN INFERMIERE SELEZIONATO"));
                }
                
                //Chiamata funzione di esportazione
                
                } catch (MainException ex) {
                    Logger.getLogger(DialogoEsportazione.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }                                               

    private void homeActionPerformedButton(java.awt.event.ActionEvent evt) {                                             
        if(GMessage.confirm(exportDialog.getString("SEI SICURO DI VOLER USCIRE DAL ")
                + exportDialog.getString("DIALOGO DELL'ESPORTAZIONE E TORNARE ALLA PIANIFICAZIONE?")) == JOptionPane.YES_OPTION){
        this.dispose();
        }
    }                                            

    private void quitActionPerformedButton(java.awt.event.ActionEvent evt) {                                             
        if(GMessage.confirm(exportDialog.getString("SEI SICURO DI VOLER ABBANDONARE")
            + exportDialog.getString(" ADISYS?")) == JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }                                            

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        if(GMessage.confirm( 
        		exportDialog.getString("SEI SICURO DI VOLER USCIRE DAL DIALOGO DELL'ESPORTAZIONE?"))
                == JOptionPane.YES_OPTION) {
             this.dispose();
         }
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (exportDialog.getString("NIMBUS").equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoEsportazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoEsportazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoEsportazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoEsportazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                window = new DialogoEsportazione(new javax.swing.JFrame(), true);
                Dimension screenResolution = Toolkit.getDefaultToolkit().getScreenSize();
                window.setLocation(new Point( (screenResolution.width - window.getWidth()) /2, (screenResolution.height - window.getHeight()) /2)  );
                window.setVisible(true);
            }
        });
    }
    
                  
    private void updateTable() throws MainException{
    	fController = RequestManager.getFCInstance();
        AbstractTableModel modelAdisys = (AbstractTableModel) fController.processRequest("visualizzaInfermieriConInterventi", null);
        nursesTable.setModel(modelAdisys);
        nursesTable = checkFullTable(nursesTable, exportDialog.getString("INFERMIERE"));
    }
    
    private JTable checkFullTable(JTable table, String label) throws MainException{
        
            if(table.getRowCount() == 0){
     
                VariableTableModel model = new VariableTableModel();
                     String[] msg = new String[1];
                        msg[0] = java.text.MessageFormat.format(
                        		exportDialog.getString("NON È STATO TROVATO ALCUN {0} REGISTRATO NEL"), 
                                new Object[] {label}) + exportDialog.getString(" SISTEMA.");
                        model.addColumn("");             
                        model.addRow(msg);
                        table.setModel(model);
                } else {
             
                       
                            TableColumnModel columnModel = table.getColumnModel();
                            TableColumn[] column = new TableColumn[columnModel.getColumnCount()];
                            String[] header = new String[columnModel.getColumnCount()];
                            for(int i = 0; i < columnModel.getColumnCount(); i++){
                                column[i] = columnModel.getColumn(i);
                                header[i] = column[i].getHeaderValue().toString();
                            }
                    
                            VariableTableModel newModel = new VariableTableModel();
                            newModel.setColumnIdentifiers(header);
                            
                            for(int i = 0; i < table.getRowCount(); i++){
                                newModel.addRow(column);
                                int j;
                                InfermiereTO to = null;
                                for(j = 0; j < table.getColumnCount(); j++){
                                    Object value = table.getValueAt(i, j);
                                    newModel.setValueAt(value, i, j);
                                    if(j == table.getColumn(InfermiereMySqlDAO.NOME_COLONNA_ID)
                                            .getModelIndex()){
                                        to = new InfermiereTO();
                                        to.setID(Integer.parseInt(value.toString()));
                                    }
                                    if(j == table.getColumn("NUMINTERVENTI").getModelIndex()){
                                        ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
                                         params.add(new Record<String, Object>("business.infermiere.InfermiereTO", to));
                                        int numInt = (int) fController.processRequest("contaInterventi", params);
                                        newModel.setValueAt(numInt, i, j);
                                    }
                                }
                                
                            }
                            table.setModel(newModel);
               
            }
            return table;
        }
        

    @Override
    public void open() {
        start();
    }

}
