/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adisys.server.boundary;

import adisys.server.strumenti.DateFormatConverter;
import adisys.server.strumenti.VariableTableModel;
import business.infermiere.InfermiereTO;
import messaggistica.MainException;
import integration.dao.InfermiereMySqlDAO;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import presentation.FrontController;
import presentation.RequestManager;
import adisys.server.strumenti.Record;
import messaggistica.GMessage;
import integration.dao.InterventoMySqlDAO;
import integration.dao.PatologiaMySqlDAO;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author Luca
 */
public class EditorInfermieri extends javax.swing.JDialog implements Boundary {
    
    private static EditorInterventi tmp = null;
    private FrontController FC;
    private static String NOME_COLONNA_CODICE;
    private static String NOME_COLONNA_NOME;
    private static String NOME_COLONNA_GRAVITA;
    private JTable tabellaTipi;
    
    public static void setEditorInterventi(EditorInterventi editor){
        tmp = editor;
    }
    
    public TableModel getTabellaTipi(){
        return tabellaTipi.getModel();
    }
    
    private static ResourceBundle editorInfermieri = ResourceBundle.getBundle("adisys/server/property/EditorInfermieri");
    private static final int LUNGHEZZAMASSIMANOME = 20;
    private static final int LUNGHEZZAMASSIMACOGNOME = 20;
    
    public static void setResourceBundle(String path, Locale locale){
        editorInfermieri = ResourceBundle.getBundle(path, locale);
    }
	/**
	 * Creates new form dialogoInfermieri
	 */
	public EditorInfermieri(java.awt.Frame parent, boolean modal) throws MainException {
		super(parent, modal);
		initComponents();
		aggiornaTabella();
		setAggiungiInfermiere();
	}

        public EditorInfermieri(){
            
        }
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        immagineTestataInfermieri = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabellaInfermieri = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        pulsanteCancella = new javax.swing.JButton();
        pulsanteModifica = new javax.swing.JButton();
        pulsanteAggiungi = new javax.swing.JButton();
        pulsanteCancellaTutti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txInfo = new javax.swing.JTextArea();
        pannelloModifica = new javax.swing.JPanel();
        txCognome = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pulsanteOK = new javax.swing.JButton();
        txNome = new javax.swing.JTextField();
        pulsanteHome = new javax.swing.JButton();
        txInfermiereSelezionato = new javax.swing.JFormattedTextField();
        txModalita = new javax.swing.JTextField();
        pulsanteEsci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(editorInfermieri.getString("TITLE")); // NOI18N
        setMinimumSize(new java.awt.Dimension(500, 480));
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        immagineTestataInfermieri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/decorazioniFinestre/Infermieri.png"))); // NOI18N

        tabellaInfermieri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabellaInfermieri.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaInfermieri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabellaInfermieriKeyPressed(evt);
            }
        });
        jScrollPane8.setViewportView(tabellaInfermieri);

        pulsanteCancella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaCancella.png"))); // NOI18N
        pulsanteCancella.setText(editorInfermieri.getString("CANCELLA INFERMIERE")); // NOI18N
        pulsanteCancella.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteCancellaActionPerformed(evt);
            }
        });

        pulsanteModifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaModifica.png"))); // NOI18N
        pulsanteModifica.setText(editorInfermieri.getString("MODIFICA INFERMIERE")); // NOI18N
        pulsanteModifica.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteModificaActionPerformed(evt);
            }
        });

        pulsanteAggiungi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaAggiungi.png"))); // NOI18N
        pulsanteAggiungi.setText(editorInfermieri.getString("AGGIUNGI INFERMIERE")); // NOI18N
        pulsanteAggiungi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteAggiungiActionPerformed(evt);
            }
        });

        pulsanteCancellaTutti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaCancellaTutti.png"))); // NOI18N
        pulsanteCancellaTutti.setText(editorInfermieri.getString("CANCELLA TUTTI GLI INFERMIERI")); // NOI18N
        pulsanteCancellaTutti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteCancellaTutti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteCancellaTuttiActionPerformed(evt);
            }
        });

        txInfo.setEditable(false);
        txInfo.setBackground(new java.awt.Color(240, 240, 240));
        txInfo.setLineWrap(true);
        txInfo.setText(editorInfermieri.getString("INSERIRE I DATI DELL'INFERMIERE E PREMERE OK")); // NOI18N
        jScrollPane1.setViewportView(txInfo);

        jLabel21.setText(editorInfermieri.getString("COGNOME INFERMIERE")); // NOI18N

        jLabel23.setText(editorInfermieri.getString("NOME INFERMIERE")); // NOI18N

        pulsanteOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/iconainseriscirossa.png"))); // NOI18N
        pulsanteOK.setText(editorInfermieri.getString("OK")); // NOI18N
        pulsanteOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteOKActionPerformed(evt);
            }
        });

        pulsanteHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/home.png"))); // NOI18N
        pulsanteHome.setText(editorInfermieri.getString("HOME")); // NOI18N
        pulsanteHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannelloModificaLayout = new javax.swing.GroupLayout(pannelloModifica);
        pannelloModifica.setLayout(pannelloModificaLayout);
        pannelloModificaLayout.setHorizontalGroup(
            pannelloModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloModificaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pannelloModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pulsanteOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pannelloModificaLayout.createSequentialGroup()
                        .addGroup(pannelloModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)
                            .addComponent(txCognome, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txNome))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelloModificaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pulsanteHome, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pannelloModificaLayout.setVerticalGroup(
            pannelloModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloModificaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pulsanteOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsanteHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pannelloModifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pulsanteAggiungi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulsanteModifica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulsanteCancella, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pulsanteCancellaTutti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pulsanteAggiungi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsanteModifica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsanteCancella)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsanteCancellaTutti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelloModifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txInfermiereSelezionato.setEditable(false);
        txInfermiereSelezionato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txModalita.setEditable(false);
        txModalita.setText(editorInfermieri.getString("OPERAZIONE")); // NOI18N

        pulsanteEsci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/arresta.png"))); // NOI18N
        pulsanteEsci.setText(editorInfermieri.getString("ABBANDONA ADISYS")); // NOI18N
        pulsanteEsci.setToolTipText(editorInfermieri.getString("ESCI DA ADISYS")); // NOI18N
        pulsanteEsci.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEsciActionPerformed(evt);
            }
        });

        jLabel1.setText(editorInfermieri.getString("STORICO")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(immagineTestataInfermieri)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulsanteEsci)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txModalita, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txInfermiereSelezionato, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(immagineTestataInfermieri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txModalita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(txInfermiereSelezionato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pulsanteEsci)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>                        

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        try {
            aggiornaTabella();
        } catch (MainException ex) {
            Logger.getLogger(EditorInfermieri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                    

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        if(GMessage.confirm(editorInfermieri.getString("SEI SICURO DI VOLER USCIRE DALL'")
                 + editorInfermieri.getString("EDITOR DEGLI INFERMIERI?")) == JOptionPane.YES_OPTION)   {
       
             this.dispose();
         }
    }                                  

    private void pulsanteEsciActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(GMessage.confirm(editorInfermieri.getString("SEI SICURO DI VOLER ABBANDONARE")
            + editorInfermieri.getString(" ADISYS?")) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }                                            

    private void pulsanteCancellaTuttiActionPerformed(java.awt.event.ActionEvent evt) {                                                      
            String messaggio = editorInfermieri.getString("CONFERMARE LA CANCELLAZIONE DI TUTTI GLI INFERMIERI?L'OPERAZIONE NON POTRA' ESSERE ANNULLATA E SARANNO CANCELLATI TUTTI GLI INTERVENTI DAL DATABASE");
            //VISUALIZZAZIONE MESSAGGIO
            if(GMessage.confirm(messaggio) == JOptionPane.YES_OPTION){
                System.out.println("Evento pulsante CancellaTuttiInfermieri");
                try {
                    if((Boolean) FC.processRequest("cancellaTuttiInfermieri", null)) {
                        System.out.println("Cancellazione di tutti gli infermieri avvenuta con successo");
                        messaggio = editorInfermieri.getString("TUTTI GLI INFERMIERI SONO STATI CANCELLATI CON SUCCESSO!");
                        if(tmp != null)
                            tmp.aggiornaInfermieri();
                        GMessage.information(messaggio);
                    } else {
                        messaggistica.GMessage.message_error(editorInfermieri.getString("CANCTUTTI"));
                    }
                } catch (MainException ex) {
                    Logger.getLogger(EditorInfermieri.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }                                                     

    private void pulsanteModificaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        setModificaInfermiere();
    }                                                

    private void pulsanteCancellaActionPerformed(java.awt.event.ActionEvent evt) {                                                 

        if(tabellaInfermieri.getSelectedRow()==-1)
        GMessage.information(editorInfermieri.getString(
                "SELEZIONARE L'INFERMIERE DA CANCELLARE E POI PREMERE IL PULSANTE CANCELLA INFERMIERE"));
        else
        {
            String nome = tabellaInfermieri.getValueAt(tabellaInfermieri.getSelectedRow(),
                    tabellaInfermieri.getColumnModel().getColumnIndex(InfermiereMySqlDAO.NOME_COLONNA_NOME)).toString();
            String cognome = tabellaInfermieri.getValueAt(tabellaInfermieri.getSelectedRow(),
                    tabellaInfermieri.getColumnModel().getColumnIndex(InfermiereMySqlDAO.NOME_COLONNA_COGNOME)).toString();
            String nominativo = nome + " " + cognome;
            String messaggio = editorInfermieri.getString("CANCELLARE L'INFERMIERE") + " " + nominativo + "?";
	    messaggio += editorInfermieri.getString("SARANNO PERSI ANCHE TUTTI I DATI RELATIVI AGLI INTERVENTI");
	    messaggio += editorInfermieri.getString("SE CI SONO INTERVENTI ASSEGNATI ALL'INFERMIERE E' OPPORTUNO MODIFICARE L'ASSEGNAZIONE.");

            //VISUALIZZAZIONE MESSAGGIO
            if(GMessage.confirm(messaggio) == JOptionPane.YES_OPTION){
                   //Recupero ID
            Object id = tabellaInfermieri.getValueAt(tabellaInfermieri.getSelectedRow(), 
                    tabellaInfermieri.getColumnModel().getColumnIndex(InfermiereMySqlDAO.NOME_COLONNA_ID));
        
            //Casting ID
            int idInt=Integer.valueOf(String.valueOf(id));
            InfermiereTO to = new InfermiereTO(idInt, nome, cognome);
            System.out.println("Evento pulsante CancellaInfermiere : "+ to);
            ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
            params.add(new Record<String, Object>("business.infermiere.InfermiereTO", to));
            try {
                if((Boolean) FC.processRequest("cancellaInfermiere", params)){
                    System.out.println("Cancellazione dell'infermiere eseguita con successo");
                    messaggio = java.text.MessageFormat.format(editorInfermieri.getString("INFERMIERE: {0} "), 
                            new Object[] {to.getNome().toUpperCase()}) + " " + to.getCognome().toUpperCase() + 
                            editorInfermieri.getString("CANCELLATO CON SUCCESSO!");
                    if(tmp != null)
                        tmp.aggiornaInfermieri();
                    GMessage.information(messaggio);
                }
                else{
                    messaggistica.GMessage.message_error(editorInfermieri.getString("CANCINFERMIERE"));
                }
            } catch (MainException ex) {
                Logger.getLogger(EditorInfermieri.class.getName()).log(Level.SEVERE, null, ex);
            }
			
            //ADISysController.cancellaInfermiere(idInt, tmp, nominativo);
            try {
                //Aggiornamento tabella
                aggiornaTabella();
            } catch (MainException ex) {
                Logger.getLogger(EditorInfermieri.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            }
        }
    }                                                

    private void pulsanteAggiungiActionPerformed(java.awt.event.ActionEvent evt) {                                                 

        setAggiungiInfermiere();
    }                                                

    private void pulsanteHomeActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(GMessage.confirm(editorInfermieri.getString("SEI SICURO DI VOLER USCIRE DALL'")
            + editorInfermieri.getString("EDITOR DEGLI INFERMIERI E TORNARE ALLA HOME?"))
        == JOptionPane.YES_OPTION) {
        this.dispose();
        }
    }                                            

    private void pulsanteOKActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //Aggiunta paziente

        rigaSelezionata = -1;
        FC = RequestManager.getFCInstance();
        if (modalita == Modalita.aggiungi) {   
            if(datiValidi()){
              if(GMessage.confirm(editorInfermieri.getString("CREARE IL NUOVO INFERMIERE")) == 
                       JOptionPane.YES_OPTION){    
                    InfermiereTO to;
                    try {
                        to = getValueJustInsert();
                        ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
                        params.add(new Record<String, Object>("business.infermiere.InfermiereTO", to));
                        try {
                            boolean ok = (boolean) FC.processRequest("creaInfermiere", params);
                            if(ok){
                            //Aggiunta al database
				String messaggio = java.text.MessageFormat.format(editorInfermieri.getString("INFERMIERE: {0} "), new Object[] {
                                    to.getNome().toUpperCase()}) + " " + to.getCognome().toUpperCase() + editorInfermieri.getString("CREATO CON SUCCESSO!");
				if(tmp != null)
                                    tmp.aggiornaInfermieri();
                                GMessage.information(messaggio);
                                setAggiungiInfermiere();
                            } else {
				//Caso infermiere non aggiunto
				String messaggio= editorInfermieri.getString("SI È VERIFICATO UN ERRORE, IMPOSSIBILE CREARE L'INFERMIERE");
                                GMessage.message_error(messaggio);
                            }
                        } catch (MainException ex) {
                            Logger.getLogger(EditorInfermieri.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (ParseException ex) {
                        Logger.getLogger(EditorInfermieri.class.getName()).log(Level.SEVERE, null, ex);
                    }				
                }
            }
        } else if (modalita == Modalita.modifica) {
            rigaSelezionata = tabellaInfermieri.getSelectedRow();
            if(datiValidi()){
                if(GMessage.confirm(editorInfermieri.getString("SEI SICURO DI MODIFICARE")) == 
                       JOptionPane.YES_OPTION){
                InfermiereTO to;
                try {
                    to = getValueJustUpdate();
                    ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
                    params.add(new Record<String, Object>("business.infermiere.InfermiereTO", to));
                    try {
                        boolean ok = (boolean) FC.processRequest("modificaInfermiere", params);
                        if(ok){
                            //Aggiunta al database
                            String messaggio = java.text.MessageFormat.format(editorInfermieri.getString("INFERMIERE: {0} "), new Object[] {
                                    tabellaInfermieri.getValueAt(rigaSelezionata,
                                    tabellaInfermieri.getColumnModel().getColumnIndex(InfermiereMySqlDAO.NOME_COLONNA_NOME)).
                                    toString().toUpperCase()}) 
                                    + " " + tabellaInfermieri.getValueAt(rigaSelezionata,
                                    tabellaInfermieri.getColumnModel().getColumnIndex(InfermiereMySqlDAO.NOME_COLONNA_COGNOME)).
                                    toString().toUpperCase(); 
                                    messaggio = messaggio + editorInfermieri.getString("MODIFICATO IN:") +
                                    to.getNome().toUpperCase() + " " + to.getCognome().toUpperCase() + editorInfermieri.getString("CON SUCCESSO!");
                                    if(tmp != null)
                                        tmp.aggiornaInfermieri();
                                    GMessage.information(messaggio);
                                setAggiungiInfermiere();
			}
			else
			{
				//Caso infermiere non aggiunto
				String messaggio= editorInfermieri.getString("SI È VERIFICATO UN ERRORE, IMPOSSIBILE MODIFICARE L'INFERMIERE");
				GMessage.message_error(messaggio);
			}
                        
                    } catch (MainException ex) {
                        Logger.getLogger(EditorInfermieri.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(EditorInfermieri.class.getName()).log(Level.SEVERE, null, ex);
                }
						
            }//DATI VALIDI
            }//IF SU JOPTION
        }
        try {
            //Aggiornamento tabella
            aggiornaTabella();
        } catch (MainException ex) {
            Logger.getLogger(EditorInfermieri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                          

    private void tabellaInfermieriKeyPressed(java.awt.event.KeyEvent evt) {                                             

    if((evt.getKeyChar()== 's' || evt.getKeyChar() == 'S') 
            && tabellaInfermieri.getColumnCount() != 1){
        //Recupero valore ID
   
        try {
            NOME_COLONNA_CODICE = PatologiaMySqlDAO.NOME_COLONNA_CODICE;
            NOME_COLONNA_NOME = PatologiaMySqlDAO.NOME_COLONNA_NOME;
            NOME_COLONNA_GRAVITA = InterventoMySqlDAO.NOME_COLONNA_GRAVITA_PATOLOGIE_TIPI_INTERVENTI;
            String dataDal = "01/01/1970";
            int colonnaID = tabellaInfermieri.getColumnModel().getColumnIndex(InfermiereMySqlDAO.NOME_COLONNA_ID);
            int id = Integer.parseInt(tabellaInfermieri.getValueAt(
                tabellaInfermieri.getSelectedRow(), colonnaID).toString());
            /*
             * Per storico intendo tutti gli interventi fino al giorno precedente
             * alla data odierna. Ho calcolato i millisecondi presenti in un giorno intero
             * e dalla data odierna in millisecondi sottraggo quelli di un giorno intero per
             * ottenere il giorno precedente
             */
            long oneDay = 86400000;
            long today = DateFormatConverter.oggi();
            long dateDiff = today - oneDay;
            String dataAl = DateFormatConverter.long2dateString(dateDiff, "dd/MM/yyyy");
           
            FC = RequestManager.getFCInstance();
            ArrayList<Record<String, Object>> params = new ArrayList<>();
            params.add(new Record<String, Object>("java.lang.Integer", id));
            params.add(new Record<String, Object>("java.lang.String", dataDal));
            params.add(new Record<String, Object>("java.lang.String", dataAl));
            AbstractTableModel modelAdisys = (AbstractTableModel) 
                    FC.processRequest("visualizzaTabellaInterventiInfermiere", params);
            int rowCount = modelAdisys.getRowCount();
            if(rowCount == 0){
                GMessage.information(editorInfermieri.getString(
                        "NESSUN INTERVENTO PRESENTE NELLO STORICO"));
            }
            else {                 
                DialogoStorico.setEditorInfermieri(this);
                tabellaTipi = new JTable(modelAdisys);
                FC = RequestManager.getFCInstance();
                String request = RequestManager.APRI_DIALOGO_STORICO;
                if(FC.processRequest(RequestManager.APRI_DIALOGO_STORICO)){
                    System.out.println("Finestra " + request + " aperta con successo.");
                }
                else{
                    messaggistica.GMessage.winNotFound(request);
                } 
            }
        } catch (MainException ex) {
            Logger.getLogger(EditorInfermieri.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }  
    }                                            

	/**
	 * @param args the command line arguments
	 */
	public static void start() {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if (editorInfermieri.getString("NIMBUS").equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditorInfermieri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditorInfermieri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditorInfermieri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditorInfermieri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				EditorInfermieri window = null;
                            try {
                                window = new EditorInfermieri(new javax.swing.JFrame(), true);
                            } catch (MainException ex) {
                                Logger.getLogger(EditorInfermieri.class.getName()).log(Level.SEVERE, null, ex);
                            }
				Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit().getScreenSize();
				window.setLocation(new Point( (risoluzioneSchermo.width - window.getWidth()) /2, (risoluzioneSchermo.height - window.getHeight()) /2)  );
				window.setVisible(true);
			}
		});
	}
        
	public void aggiornaTabella() throws MainException {
		//apre il front controller per farsi dare i dati da inserire nella tabella
		FC = RequestManager.getFCInstance();
		AbstractTableModel modelAdisys = (AbstractTableModel) FC.processRequest("visualizzaInfermieri", null);
		tabellaInfermieri.setModel(modelAdisys);
		
                if(tabellaInfermieri.getRowCount() == 0){
                    VariableTableModel modello = new VariableTableModel();
                    modello.addColumn("");
                     String[] msg = {editorInfermieri.getString("NON È STATO TROVATO ALCUN INFERMIERE REGISTRATO NEL")
                        + editorInfermieri.getString(" SISTEMA.")};
                     modello.addRow(msg);
                     tabellaInfermieri.setModel(modello);
                     pulsanteModifica.setVisible(false);
                     pulsanteCancella.setVisible(false);
                     pulsanteCancellaTutti.setVisible(false);
                     jLabel1.setVisible(false);
                     return;
                }
                 if(pulsanteModifica.isVisible() == false){
                     pulsanteModifica.setVisible(true);
                     pulsanteCancella.setVisible(true);
                     pulsanteCancellaTutti.setVisible(true);
                     jLabel1.setVisible(true);
                 }
                if(rigaSelezionata != -1)
                    tabellaInfermieri.setRowSelectionInterval(rigaSelezionata, rigaSelezionata);
	}

	public boolean datiValidi()
	{
		String messaggio =editorInfermieri.getString("ATTENZIONE:");
		int errori=0;
		if (txNome.getText().isEmpty())
		{
			errori++;
			messaggio += editorInfermieri.getString("NOME INFERMIERE VUOTO");
		} else if(txNome.getText().length() > LUNGHEZZAMASSIMANOME){
                        errori++;
			messaggio += editorInfermieri.getString("NOME INFERMIERE TROPPO LUNGO (MAX");
                        messaggio += LUNGHEZZAMASSIMANOME + " ";
                        messaggio += editorInfermieri.getString("CAR)");
                } 
                boolean numeric = false;
                for(int i = 0; i < txNome.getText().length(); i++){
                    if(txNome.getText().toCharArray()[i] >= '0' && txNome.getText().toCharArray()[i] <= '9'){
                        numeric = true;
                        break;
                    }
                }
                if(numeric == true){
                        errori++;
			messaggio += editorInfermieri.getString("IL NOME DELL'INFERMIERE CONTIENE CARATTERI NUMERICI");
                }
		if(txCognome.getText().isEmpty())
		{
			errori++;
			messaggio += editorInfermieri.getString("COGNOME INFERMIERE VUOTO");
		} else if(txCognome.getText().length() > LUNGHEZZAMASSIMACOGNOME){
                        errori++;
			messaggio += editorInfermieri.getString("COGNOME INFERMIERE TROPPO LUNGO (MAX");
                        messaggio += LUNGHEZZAMASSIMACOGNOME + " ";
                        messaggio += editorInfermieri.getString("CAR)");
                }
                numeric = false;
                for(int i = 0; i < txCognome.getText().length(); i++){
                    if(txCognome.getText().toCharArray()[i] >= '0' && txCognome.getText().toCharArray()[i] <= '9'){
                        numeric = true;
                        break;
                    }
                }
                if(numeric == true){
                        errori++;
			messaggio += editorInfermieri.getString("IL COGNOME DELL'INFERMIERE CONTIENE CARATTERI NUMERICI");
                }
		if (errori==0) return true;
		else 
		{
			messaggio+= editorInfermieri.getString("\n")+String.valueOf(errori)+editorInfermieri.getString(" ERRORI RILEVATI.");
			GMessage.message_error(messaggio);
			return false;
		}

	}

        /**
	 * Restituisce i valori dei campi appena inseriti
	 * @return una struttura dati di String con i valori appena inseriti
	 * @throws ParseException 
	*/
	private InfermiereTO getValueJustInsert() throws ParseException{
		
		InfermiereTO to = new InfermiereTO(txNome.getText().toUpperCase(), txCognome.getText().toUpperCase());
		System.out.println(to);
		
		return to;
		
	}
        
        /**
	 * Restituisce i valori dei campi appena inseriti
	 * @return una struttura dati di String con i valori appena inseriti
	 * @throws ParseException 
	*/
	private InfermiereTO getValueJustUpdate() throws ParseException{
		
		InfermiereTO to = new InfermiereTO(
                        Integer.parseInt(txInfermiereSelezionato.getText()), 
                        txNome.getText().toUpperCase(), txCognome.getText().toUpperCase());
		System.out.println(to);
		
		return to;
		
	}
	
	private void setAggiungiInfermiere()
	{
		//Setta la variabile modalita
		modalita=Modalita.aggiungi;
                txModalita.setText(modAggiungi);
                txInfermiereSelezionato.setText("");
		//Setta il modulo per l'inserimento
		txInfermiereSelezionato.setText("");
		txNome.setText("");
		txCognome.setText("");
		txInfo.setText(editorInfermieri.getString("AGGIUNTA NUOVO INFERMIERE INSERIRE NOME E COGNOME E PREMERE OK"));
	}

	private void setModificaInfermiere()
	{

		if(tabellaInfermieri.getSelectedRow()==-1)
			GMessage.information(editorInfermieri.getString("SELEZIONARE L'INFERMIERE DA MODIFICARE E POI PREMERE IL PULSANTE MODIFICA INFERMIERE"));
		else
		{

			//Setta la variabile modalita
			modalita = Modalita.modifica;               
                        txModalita.setText(modModifica);
                        txInfermiereSelezionato.setText(tabellaInfermieri.getValueAt(tabellaInfermieri.getSelectedRow(), 
                                tabellaInfermieri.getColumnModel().getColumnIndex(InfermiereMySqlDAO.NOME_COLONNA_ID)).toString());
			//Recupero valori ID NOME COGNOME
			Object id = tabellaInfermieri.getValueAt(tabellaInfermieri.getSelectedRow(), tabellaInfermieri.getColumnModel().getColumnIndex(InfermiereMySqlDAO.NOME_COLONNA_ID));
			Object nome= tabellaInfermieri.getValueAt(tabellaInfermieri.getSelectedRow(), tabellaInfermieri.getColumnModel().getColumnIndex(InfermiereMySqlDAO.NOME_COLONNA_NOME));
			Object cognome=tabellaInfermieri.getValueAt(tabellaInfermieri.getSelectedRow(), tabellaInfermieri.getColumnModel().getColumnIndex(InfermiereMySqlDAO.NOME_COLONNA_COGNOME));

			//Setta il modulo per l'inserimento
			txNome.setText(String.valueOf(nome));
			txCognome.setText(String.valueOf(cognome));
			txInfo.setText(editorInfermieri.getString("MODIFICA INFERMIERE MODIFICARE NOME E COGNOME E PREMERE OK."));
		}   }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel immagineTestataInfermieri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pannelloModifica;
    private javax.swing.JButton pulsanteAggiungi;
    private javax.swing.JButton pulsanteCancella;
    private javax.swing.JButton pulsanteCancellaTutti;
    private javax.swing.JButton pulsanteEsci;
    private javax.swing.JButton pulsanteHome;
    private javax.swing.JButton pulsanteModifica;
    private javax.swing.JButton pulsanteOK;
    private javax.swing.JTable tabellaInfermieri;
    private javax.swing.JTextField txCognome;
    private javax.swing.JFormattedTextField txInfermiereSelezionato;
    private javax.swing.JTextArea txInfo;
    private javax.swing.JTextField txModalita;
    private javax.swing.JTextField txNome;
    // End of variables declaration                   

    private final String modAggiungi = editorInfermieri.getString("AGGIUNGI");
    private final String modModifica = editorInfermieri.getString("MODIFICA N.");

    @Override
    public void apri() {
        start();
    }
      
    private enum Modalita{aggiungi, modifica};
    private Modalita modalita;
    private int rigaSelezionata = -1;
}
