package adisys.server.boundary;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import business.intervento.PatologieTipoIntervento;
import adisys.server.strumenti.VariableTableModel;
import business.patologia.PatologiaTO;
import messaggistica.GMessage;
import messaggistica.MainException;
import integration.dao.InterventoMySqlDAO;
import integration.dao.PatologiaMySqlDAO;
import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import presentation.FrontController;
import presentation.RequestManager;
/**
*
* @author Gianmarco Divittorio
* @author Nicola Gazzilli
*/
public class EditorRipetiPatologie extends javax.swing.JDialog implements Boundary {
    
    private static EditorInterventi tmp = null;
    private PatologieTipoIntervento listaPatologieTipoIntervento;

    private int colonnaCodice;
    private int colonnaNome;
    private int colonnaGravita;
    
    private static String NOME_COLONNA_CODICE;
    private static String NOME_COLONNA_NOME;
    private static String NOME_COLONNA_GRAVITA;
    private static ResourceBundle editorRipetiPatologie = ResourceBundle.getBundle("adisys/server/property/EditorRipetiPatologie");
    private FrontController FC;
    
    public static void setResourceBundle(String path, Locale locale){
             editorRipetiPatologie = ResourceBundle.getBundle(path, locale);
    }
    
    public static void setEditorInterventi(EditorInterventi editor){
        tmp = editor;
    }
   
	/**
	 * Creates new form dialogoPatologieTipoIntervento
	 */
	public EditorRipetiPatologie(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
                aggiornaTabella();
	}
        
        public EditorRipetiPatologie(){
            
        }
        
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        immagineTestataRipPatologie = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabellaPatologie = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pulsanteAssociaPatologie = new javax.swing.JButton();
        aggiungiPatologie = new javax.swing.JButton();
        pulsanteHome1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(editorRipetiPatologie.getString("TITLE")); // NOI18N
        setMinimumSize(null);
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        immagineTestataRipPatologie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/decorazioniFinestre/PatologiaRipetiIntervento.png"))); // NOI18N

        tabellaPatologie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabellaPatologie.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tabellaPatologie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabellaPatologieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabellaPatologieMouseExited(evt);
            }
        });
        jScrollPane8.setViewportView(tabellaPatologie);

        jLabel1.setText(editorRipetiPatologie.getString("SELEZIONARE UNA O PIU DELLE PATOLOGIE GIA IMPOSTATE E PREMERE IL PULSANTE ASSOCIA SE NON SI DESIDERA ALTRO, OPPURE IL PULSANTE AGGIUNGI SE SI DESIDERA AGGIUNGERE NUOVE PATOLOGIE")); // NOI18N

        pulsanteAssociaPatologie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/iconainseriscirossa.png"))); // NOI18N
        pulsanteAssociaPatologie.setText(editorRipetiPatologie.getString("ASSOCIA PATOLOGIE ALL'INTERVENTO")); // NOI18N
        pulsanteAssociaPatologie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteAssociaPatologieActionPerformed(evt);
            }
        });

        aggiungiPatologie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/freccia_verde_256x256.png"))); // NOI18N
        aggiungiPatologie.setText(editorRipetiPatologie.getString("AGGIUNGI NUOVE PATOLOGIE")); // NOI18N
        aggiungiPatologie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiungiPatologieActionPerformed(evt);
            }
        });

        pulsanteHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/arresta.png"))); // NOI18N
        pulsanteHome1.setText(editorRipetiPatologie.getString("ABBANDONA")); // NOI18N
        pulsanteHome1.setToolTipText(editorRipetiPatologie.getString("TOOLTIP ABBANDONA")); // NOI18N
        pulsanteHome1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteHome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(immagineTestataRipPatologie)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aggiungiPatologie)
                        .addGap(131, 131, 131)
                        .addComponent(pulsanteHome1)
                        .addGap(156, 156, 156)
                        .addComponent(pulsanteAssociaPatologie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(immagineTestataRipPatologie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aggiungiPatologie, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pulsanteAssociaPatologie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pulsanteHome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
         String msg = editorRipetiPatologie.getString(
                "SEI SICURO DI VOLER USCIRE DAL PANNELLO?VERRAI INDIRIZZATO ALL'EDITOR PER L'IMPOSTAZIONE DI NUOVE PATOLOGIE.");
        if(GMessage.confirm(msg) == JOptionPane.YES_OPTION) {
            request(RequestManager.APRI_EDITOR_PATOLOGIE_TIPO_INTERVENTO);
            this.dispose();
        }
    }                                  

    private void request(String request){
        FC = RequestManager.getFCInstance();
        if(FC.processRequest(request)){
            System.out.println("Finestra " + request + " aperta con successo.");
        }
        else{
            messaggistica.GMessage.winNotFound(request);
        }
    }
    
    private void pulsanteAssociaPatologieActionPerformed(java.awt.event.ActionEvent evt) {                                                         
            
        if(tabellaPatologie.getSelectedRows().length == 0)
            GMessage.message_error(editorRipetiPatologie.getString("NESSUNA PATOLOGIA SELEZIONATA"));
        else {
            String msg = editorRipetiPatologie.getString("CONFERMI DI AGGIUNGERE QUESTE PATOLOGIE?");
            if(GMessage.confirm(msg) == JOptionPane.YES_OPTION) {
            
                this.listaPatologieTipoIntervento = tmp.getPatologieTipoIntervento();
                //Intestazioni
            
                int numberRows = tabellaPatologie.getSelectedRows().length;
                VariableTableModel modello = (VariableTableModel) tmp.getModelTabellaPatologie();
           
                modello.setRowCount(numberRows);
             
                tmp.setModelTabellaPatologie(modello);

                ArrayList<PatologiaTO> tmpList = new ArrayList<>();
            
                for(int i = 0; i < numberRows; i++){
               
                        String codice = String.valueOf(tabellaPatologie.getValueAt(i, colonnaCodice));
                        String nome = String.valueOf(tabellaPatologie.getValueAt(i, colonnaNome));
                        int gravita = Integer.parseInt(String.valueOf( tabellaPatologie.getValueAt(i, colonnaGravita)));
                        PatologiaTO newPatologia = new PatologiaTO(codice, nome, gravita);
                        tmpList.add(newPatologia);
                     
                }
                //int rowInsertTipo = tmp.getTabellaTipiIntervento().getRowCount() - 1;
                listaPatologieTipoIntervento.setListaPatologieTipoIntervento(tmpList);
                tmp.setPatologieTipoIntervento(listaPatologieTipoIntervento);
                tmp.getTabellaTipiIntervento().setRowSelectionInterval(
                        tmp.getTabellaTipiIntervento().getRowCount() - 1, 
                        tmp.getTabellaTipiIntervento().getRowCount() - 1);
                this.dispose();
            }
        }
    }                                                        

     public VariableTableModel getModelloPatologieEditor() throws MainException
        {   
            FC = RequestManager.getFCInstance();
            TableModel tabellaPatologie = (AbstractTableModel) FC.processRequest("visualizzaPatologie", null);
            VariableTableModel tabellaEditorPatologie = new VariableTableModel();
            if(tabellaPatologie.getRowCount() != 0){
                for(int i = 0; i < tabellaPatologie.getColumnCount(); i++){
                    tabellaEditorPatologie.addColumn(tabellaPatologie.getColumnName(i));
                }
                tabellaEditorPatologie.addColumn(InterventoMySqlDAO.NOME_COLONNA_GRAVITA_PATOLOGIE_TIPI_INTERVENTI);
                tabellaEditorPatologie.setRowCount(tabellaPatologie.getRowCount());
                for(int i = 0; i < tabellaEditorPatologie.getRowCount(); i++){
                    for(int k = 0; k < tabellaEditorPatologie.getColumnCount() - 1; k++){
                        tabellaEditorPatologie.setValueAt(tabellaPatologie.getValueAt(i, k), i, k);
                    }
                }
            } 
            //Creazione modello
            return tabellaEditorPatologie;
    }
     
    private void aggiungiPatologieActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        if(tabellaPatologie.getSelectedRows().length != 0){
            String msg = java.text.MessageFormat.format(editorRipetiPatologie.getString("SONO STATE SELEZIONATE {0}"), new Object[] {tabellaPatologie.getSelectedRowCount()})                    + editorRipetiPatologie.getString(" PATOLOGIA/E. SE SI SCEGLIE DI PROSEGUIRE SARANNO AGGIUNTE LE PATOLOGIE SELEZIONATE ")
                    + editorRipetiPatologie.getString("E SI AVRÀ LA POSSIBILITÀ DI AGGIUNGERNE DELLE ALTRE.")
                    + editorRipetiPatologie.getString("IL PULSANTE NO PERMETTE DI AGGIUNGERE NUOVE PATOLOGIE SENZA CONSIDERARE QUELLE ")
                    + editorRipetiPatologie.getString("SELEZIONATE.SE SI VUOLE SOLO AGGIUNGERE QUELLE SELEZIONATE")
                    + editorRipetiPatologie.getString(" ANNULLARE L'OPERAZIONE E PREMERE IL PULSANTE ASSOCIA PATOLOGIE SELEZIONATE.");
            int conferma = GMessage.yes_no_cancel_message(msg);
            if(conferma == JOptionPane.YES_OPTION) { 
                ArrayList<PatologiaTO> tmpList = new ArrayList<>();
                int numberRows = tabellaPatologie.getSelectedRowCount();
                for(int i = 0; i < numberRows; i++){
               
                        String codice = String.valueOf(tabellaPatologie.getValueAt(i, colonnaCodice));
                        String nome = String.valueOf(tabellaPatologie.getValueAt(i, colonnaNome));
                        int gravita = Integer.parseInt(String.valueOf( tabellaPatologie.getValueAt(i, colonnaGravita)));
                        PatologiaTO newPatologia = new PatologiaTO(codice, nome, gravita);
                        tmpList.add(newPatologia);
                     
                }
                VariableTableModel modello = (VariableTableModel) tmp.getModelTabellaPatologie();
           
                modello.setRowCount(numberRows);
             
                tmp.setModelTabellaPatologie(modello);
                listaPatologieTipoIntervento.setListaPatologieTipoIntervento(tmpList);
                tmp.setPatologieTipoIntervento(listaPatologieTipoIntervento);
                EditorPatologieTipoIntervento.setModifica(1);
                EditorPatologieTipoIntervento.setEditorInterventi(tmp);
                request(RequestManager.APRI_EDITOR_PATOLOGIE_TIPO_INTERVENTO);
                this.dispose();
               
            } else if(conferma == JOptionPane.NO_OPTION){
                this.dispose();
                request(RequestManager.APRI_EDITOR_PATOLOGIE_TIPO_INTERVENTO);
            }
        } else {
            String msg = editorRipetiPatologie.getString("SEI SICURO DI VOLER LASCIARE L'EDITOR PER L'INSERIMENTO DI PATOLOGIE GIÀ")
                    + editorRipetiPatologie.getString(" IMPOSTATE E ANDARE ALL'EDITOR PER L'IMPOSTAZIONE DI NUOVE PATOLOGIE?");  
            int conferma = GMessage.confirm(msg);
            if(conferma == JOptionPane.YES_OPTION){
            	EditorPatologieTipoIntervento.setModifica(0);
                request(RequestManager.APRI_EDITOR_PATOLOGIE_TIPO_INTERVENTO);
                this.dispose();
            }
        }
    }                                                 

    private void tabellaPatologieMouseEntered(java.awt.event.MouseEvent evt) {                                              
        try {
            Robot robot = new Robot();

            // Simulate a key press
            robot.keyPress(KeyEvent.VK_CONTROL);
        } catch (AWTException e) {
            e.printStackTrace();
        }
    }                                             

    private void tabellaPatologieMouseExited(java.awt.event.MouseEvent evt) {                                             
        try {
            Robot robot = new Robot();

            // Simulate a key press
            robot.keyRelease(KeyEvent.VK_CONTROL);
        } catch (AWTException e) {
            e.printStackTrace();
        }
    }                                            

    private void pulsanteHome1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(GMessage.confirm(editorRipetiPatologie.getString("SEI SICURO DI VOLER ABBANDONARE")
            + editorRipetiPatologie.getString(" ADISYS?")) == JOptionPane.YES_NO_OPTION) {
        System.exit(0);
        }
    }                                             
       
	/**
	 * @param args the command line arguments
	 */
	public static void start() {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if (editorRipetiPatologie.getString("NIMBUS").equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditorRipetiPatologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditorRipetiPatologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditorRipetiPatologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditorRipetiPatologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				EditorRipetiPatologie window = new EditorRipetiPatologie(new javax.swing.JFrame(), true);
				Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit().getScreenSize();
				window.setLocation(new Point( (risoluzioneSchermo.width - window.getWidth()) /2, (risoluzioneSchermo.height - window.getHeight()) /2)  );

				window.setVisible(true);
			}
		});
	}

        public void aggiornaTabella(){
                
            NOME_COLONNA_CODICE = PatologiaMySqlDAO.NOME_COLONNA_CODICE;
            NOME_COLONNA_NOME = PatologiaMySqlDAO.NOME_COLONNA_NOME;
            NOME_COLONNA_GRAVITA = InterventoMySqlDAO.NOME_COLONNA_GRAVITA_PATOLOGIE_TIPI_INTERVENTI;
            VariableTableModel modello = getModelloPatologieVuoto();

            tabellaPatologie.setModel(modello);
            colonnaCodice = tabellaPatologie.getColumn(NOME_COLONNA_CODICE).getModelIndex();
            colonnaNome = tabellaPatologie.getColumn(NOME_COLONNA_NOME).getModelIndex();
            colonnaGravita = tabellaPatologie.getColumn(NOME_COLONNA_GRAVITA).getModelIndex();
            
            listaPatologieTipoIntervento = tmp.getPatologieTipoIntervento();
            ArrayList<PatologiaTO>[] listaPatologie = this.listaPatologieTipoIntervento.getListaInterventiPatologie();
            int cont = 0;
            boolean trovato;
            for(ArrayList<PatologiaTO> e : listaPatologie){
                for(PatologiaTO p : e){
                    trovato = false;
                    for(int i = 0; i < tabellaPatologie.getRowCount(); i++){
                        if(p.getCodice() == tabellaPatologie.getValueAt(i, colonnaCodice)){
                            trovato = true;
                            break;
                        }
                    }
                    if(trovato != true){
                        cont++;
                        modello.setRowCount(cont);
                        tabellaPatologie.setModel(modello);
                        tabellaPatologie.setValueAt(p.getCodice(), cont - 1, colonnaCodice);
                        tabellaPatologie.setValueAt(p.getNome(), cont - 1, colonnaNome);
                        tabellaPatologie.setValueAt(p.getGravita(), cont - 1, colonnaGravita);
                    }
                }
                
            }
            
	}//aggiorna tabella
        
        public VariableTableModel getModelloPatologieVuoto() {
            //Intestazioni
            VariableTableModel tabellaPatologieVuota = new VariableTableModel();
            tabellaPatologieVuota.addColumn(PatologiaMySqlDAO.NOME_COLONNA_CODICE);
            tabellaPatologieVuota.addColumn(PatologiaMySqlDAO.NOME_COLONNA_NOME);
            tabellaPatologieVuota.addColumn(InterventoMySqlDAO.NOME_COLONNA_GRAVITA_PATOLOGIE_TIPI_INTERVENTI);
           
            //Creazione modello
            return tabellaPatologieVuota;
        }
        
    // Variables declaration - do not modify                     
    private javax.swing.JButton aggiungiPatologie;
    private javax.swing.JLabel immagineTestataRipPatologie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton pulsanteAssociaPatologie;
    private javax.swing.JButton pulsanteHome1;
    private javax.swing.JTable tabellaPatologie;
    // End of variables declaration                   

    @Override
    public void open() {
        start();
    }
 
}
