/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adisys.server.boundary;

import messaggistica.MainException;
import integration.dao.InfermiereMySqlDAO;
import integration.dao.InterventoMySqlDAO;
import integration.dao.PatologiaMySqlDAO;
import integration.dao.PazienteMySqlDAO;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import presentation.FrontController;
import presentation.RequestManager;
import adisys.server.strumenti.Record;
import messaggistica.GMessage;

/**
*
* @author Gianmarco Divittorio
* @author Nicola Gazzilli
*/
public class EditorDatabase extends javax.swing.JFrame implements Boundary {
    private static ResourceBundle editorDatabase = ResourceBundle.getBundle("adisys/server/property/EditorDatabase");
    private FrontController FC;
    
    public static void setResourceBundle(String path, Locale locale){
        editorDatabase = ResourceBundle.getBundle(path, locale);
    }

	/**
	 * Creates new form ADISysGUI
	 */
	public EditorDatabase() {
		initComponents();
		 
                txNomeTabella.setVisible(false);
                txNomeCampo1.setVisible(false);
                txNomeCampo2.setVisible(false);
                txNomeCampo3.setVisible(false);
                txNomeCampo4.setVisible(false);
                txNomeCampo5.setVisible(false);
                txNomeCampo6.setVisible(false);
                txNomeCampo7.setVisible(false);
                txNomeCampo8.setVisible(false);
                txNomeCampo9.setVisible(false);
                txNomeCampo10.setVisible(false);
                jLabelTabella.setVisible(false);
                jLabelCampo1.setVisible(false);
                jLabelCampo2.setVisible(false);
                jLabelCampo3.setVisible(false);
                jLabelCampo4.setVisible(false);
                jLabelCampo5.setVisible(false);
                jLabelCampo6.setVisible(false);
                jLabelCampo7.setVisible(false);
                jLabelCampo8.setVisible(false);
                jLabelCampo9.setVisible(false);
                jLabelCampo10.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        intestazione = new javax.swing.JLabel();
        buttonTabPazienti = new javax.swing.JButton();
        buttonTabInfermieri = new javax.swing.JButton();
        buttonTabPatologie = new javax.swing.JButton();
        buttonTabInterventi = new javax.swing.JButton();
        buttonTabTipiIntervento = new javax.swing.JButton();
        buttonTabPatologieTipiIntervento = new javax.swing.JButton();
        buttonTabCellulariPazienti = new javax.swing.JButton();
        jLabelTabella = new javax.swing.JLabel();
        txNomeTabella = new javax.swing.JTextField();
        pulsanteHome3 = new javax.swing.JButton();
        pulsanteOK = new javax.swing.JButton();
        pulsanteIndietro = new javax.swing.JButton();
        pulsanteServer = new javax.swing.JButton();
        pulsanteResetta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txInfoData = new javax.swing.JTextArea();
        jLabelCampo1 = new javax.swing.JLabel();
        jLabelCampo2 = new javax.swing.JLabel();
        jLabelCampo3 = new javax.swing.JLabel();
        jLabelCampo4 = new javax.swing.JLabel();
        jLabelCampo5 = new javax.swing.JLabel();
        txNomeCampo1 = new javax.swing.JTextField();
        txNomeCampo2 = new javax.swing.JTextField();
        txNomeCampo3 = new javax.swing.JTextField();
        txNomeCampo4 = new javax.swing.JTextField();
        txNomeCampo5 = new javax.swing.JTextField();
        jLabelCampo6 = new javax.swing.JLabel();
        jLabelCampo7 = new javax.swing.JLabel();
        jLabelCampo8 = new javax.swing.JLabel();
        jLabelCampo9 = new javax.swing.JLabel();
        txNomeCampo6 = new javax.swing.JTextField();
        txNomeCampo7 = new javax.swing.JTextField();
        txNomeCampo8 = new javax.swing.JTextField();
        txNomeCampo9 = new javax.swing.JTextField();
        jLabelCampo10 = new javax.swing.JLabel();
        txNomeCampo10 = new javax.swing.JTextField();
        barraDeiMenu = new javax.swing.JMenuBar();

       

        intestazione.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/decorazioniFinestre/EditorDatabase.png"))); // NOI18N

        buttonTabPazienti.setText(editorDatabase.getString("TABELLA PAZIENTI")); // NOI18N
        buttonTabPazienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTabPazientiActionPerformed(evt);
            }
        });

        buttonTabInfermieri.setText(editorDatabase.getString("TABELLA INFERMIERI")); // NOI18N
        buttonTabInfermieri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTabInfermieriActionPerformed(evt);
            }
        });

        buttonTabPatologie.setText(editorDatabase.getString("TABELLA PATOLOGIE")); // NOI18N
        buttonTabPatologie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTabPatologieActionPerformed(evt);
            }
        });

        buttonTabInterventi.setText(editorDatabase.getString("TABELLA INTERVENTI")); // NOI18N
        buttonTabInterventi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTabInterventiActionPerformed(evt);
            }
        });

        buttonTabTipiIntervento.setText(editorDatabase.getString("TABELLA TIPI INTERVENTO")); // NOI18N
        buttonTabTipiIntervento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTabTipiInterventoActionPerformed(evt);
            }
        });

        buttonTabPatologieTipiIntervento.setText(editorDatabase.getString("TABELLA PATOLOGIE TIPI INTERVENTO")); // NOI18N
        buttonTabPatologieTipiIntervento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTabPatologieTipiInterventoActionPerformed(evt);
            }
        });

        buttonTabCellulariPazienti.setText(editorDatabase.getString("TABELLA CELLULARI PAZIENTI")); // NOI18N
        buttonTabCellulariPazienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTabCellulariPazientiActionPerformed(evt);
            }
        });

        jLabelTabella.setText(editorDatabase.getString("NOME TABELLA:")); // NOI18N

        pulsanteHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/arresta.png"))); // NOI18N
        pulsanteHome3.setText(editorDatabase.getString("ABBANDONA ADISYS")); // NOI18N
        pulsanteHome3.setToolTipText(editorDatabase.getString("ESCI DA ADISYS")); // NOI18N
        pulsanteHome3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteHome3ActionPerformed(evt);
            }
        });

        pulsanteOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/iconainseriscirossa.png"))); // NOI18N
        pulsanteOK.setText(editorDatabase.getString("CONFERMA")); // NOI18N
        pulsanteOK.setToolTipText(editorDatabase.getString("CONFERMA LE MODIFICHE NEL FORM")); // NOI18N
        pulsanteOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteOKActionPerformed(evt);
            }
        });

      

      
        pulsanteResetta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/reset.png"))); // NOI18N
        pulsanteResetta.setText(editorDatabase.getString("RESETTA")); // NOI18N
        pulsanteResetta.setToolTipText(editorDatabase.getString("RESETTA LE MODIFICHE NEL FORM")); // NOI18N
        pulsanteResetta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteResettaActionPerformed(evt);
            }
        });

        txInfoData.setEditable(false);
        txInfoData.setBackground(new java.awt.Color(240, 240, 240));
        txInfoData.setLineWrap(true);
        txInfoData.setText(editorDatabase.getString("Benvenuto in ADISysDatabase versione 1.0. In questo pannello, puramente a scopo didattico, è possibile modificare i nomi delle tabelle del DBMS con cui ADISys è relazionato, con gli annessi attributi, al fine di verificare che il sistema offra un comportamento dinamico senza sollevare alcun tipo di errore.")); // NOI18N
        jScrollPane1.setViewportView(txInfoData);

        jLabelCampo1.setText(editorDatabase.getString("CAMPO 1:")); // NOI18N

        jLabelCampo2.setText(editorDatabase.getString("CAMPO 2:")); // NOI18N

        jLabelCampo3.setText(editorDatabase.getString("CAMPO 3:")); // NOI18N

        jLabelCampo4.setText(editorDatabase.getString("CAMPO 4:")); // NOI18N

        jLabelCampo5.setText(editorDatabase.getString("CAMPO 5:")); // NOI18N

        jLabelCampo6.setText(editorDatabase.getString("CAMPO 6:")); // NOI18N

        jLabelCampo7.setText(editorDatabase.getString("CAMPO 7:")); // NOI18N

        jLabelCampo8.setText(editorDatabase.getString("CAMPO 8:")); // NOI18N

        jLabelCampo9.setText(editorDatabase.getString("CAMPO 9:")); // NOI18N

        txNomeCampo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeCampo9ActionPerformed(evt);
            }
        });

        jLabelCampo10.setText("Campo 10:");

        barraDeiMenu.setRequestFocusEnabled(false);
        setJMenuBar(barraDeiMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(intestazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonTabPatologie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonTabCellulariPazienti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonTabPatologieTipiIntervento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonTabTipiIntervento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonTabInterventi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonTabInfermieri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonTabPazienti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pulsanteHome3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txNomeCampo5))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txNomeCampo4))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txNomeCampo3))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txNomeCampo2))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txNomeCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCampo6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelCampo7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelCampo8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelCampo9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelCampo10)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabelTabella)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txNomeTabella, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txNomeCampo6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txNomeCampo7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txNomeCampo8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txNomeCampo9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txNomeCampo10))
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(pulsanteServer, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(pulsanteIndietro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pulsanteResetta)
                                .addGap(18, 18, 18)
                                .addComponent(pulsanteOK)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(intestazione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTabPazienti)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTabella)
                        .addComponent(txNomeTabella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonTabCellulariPazienti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTabInfermieri)
                    .addComponent(jLabelCampo1)
                    .addComponent(txNomeCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCampo6)
                    .addComponent(txNomeCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTabInterventi)
                    .addComponent(jLabelCampo2)
                    .addComponent(txNomeCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCampo7)
                    .addComponent(txNomeCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTabTipiIntervento)
                    .addComponent(jLabelCampo3)
                    .addComponent(txNomeCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCampo8)
                    .addComponent(txNomeCampo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTabPatologieTipiIntervento)
                    .addComponent(jLabelCampo4)
                    .addComponent(txNomeCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCampo9)
                    .addComponent(txNomeCampo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTabPatologie)
                    .addComponent(jLabelCampo5)
                    .addComponent(txNomeCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCampo10)
                    .addComponent(txNomeCampo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulsanteOK)
                    .addComponent(pulsanteResetta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pulsanteHome3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pulsanteIndietro)
                        .addComponent(pulsanteServer)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        
    
    public void unsetCampi(JLabel label, JTextField campo){
        label.setVisible(false);
        campo.setVisible(false);
    }
    
    public void setCampi(JLabel label, JTextField campo){
        label.setVisible(true);
        campo.setVisible(true);
    }
    
    private void formPazienti(){
        setCampi(jLabelTabella, txNomeTabella);
        setCampi(jLabelCampo1, txNomeCampo1);
        setCampi(jLabelCampo2, txNomeCampo2);
        txNomeTabella.setText(PazienteMySqlDAO.NOME_TABELLA);
        txNomeCampo1.setText(PazienteMySqlDAO.NOME_COLONNA_ID);
        txNomeCampo2.setText(PazienteMySqlDAO.NOME_COLONNA_NOME);
        setCampi(jLabelCampo3, txNomeCampo3);
        setCampi(jLabelCampo4, txNomeCampo4);
        txNomeCampo3.setText(PazienteMySqlDAO.NOME_COLONNA_COGNOME);
        txNomeCampo4.setText(PazienteMySqlDAO.NOME_COLONNA_DATA_NASCITA);
        unsetCampi(jLabelCampo5, txNomeCampo5);
        unsetCampi(jLabelCampo6, txNomeCampo6);
        unsetCampi(jLabelCampo7, txNomeCampo7);
        unsetCampi(jLabelCampo8, txNomeCampo8);
        unsetCampi(jLabelCampo9, txNomeCampo9);
        unsetCampi(jLabelCampo10, txNomeCampo10);
    }
    
    private void buttonTabCellulariPazientiActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        tabella = Tabella.cellulari;
        formCellulari();
    }                                                          

    private void formCellulari(){
        setCampi(jLabelTabella, txNomeTabella);
        setCampi(jLabelCampo1, txNomeCampo1);
        setCampi(jLabelCampo2, txNomeCampo2);
        txNomeTabella.setText(PazienteMySqlDAO.NOME_TABELLA_CELLULARI);
        txNomeCampo1.setText(PazienteMySqlDAO.NOME_COLONNA_PAZIENTE_CELLULARI);
        txNomeCampo2.setText(PazienteMySqlDAO.NOME_COLONNA_NUMERO_CELLULARI);
        unsetCampi(jLabelCampo3, txNomeCampo3);
        unsetCampi(jLabelCampo4, txNomeCampo4);
        unsetCampi(jLabelCampo5, txNomeCampo5);
        unsetCampi(jLabelCampo6, txNomeCampo6);
        unsetCampi(jLabelCampo7, txNomeCampo7);
        unsetCampi(jLabelCampo8, txNomeCampo8);
        unsetCampi(jLabelCampo9, txNomeCampo9);
        unsetCampi(jLabelCampo10, txNomeCampo10);
    }
    
    private void buttonTabInfermieriActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        tabella = Tabella.infermieri;
        formInfermieri();
    }                                                   

    private void formInfermieri(){
        setCampi(jLabelTabella, txNomeTabella);
        setCampi(jLabelCampo1, txNomeCampo1);
        setCampi(jLabelCampo2, txNomeCampo2);
        txNomeTabella.setText(InfermiereMySqlDAO.NOME_TABELLA);
        txNomeCampo1.setText(InfermiereMySqlDAO.NOME_COLONNA_ID);
        txNomeCampo2.setText(InfermiereMySqlDAO.NOME_COLONNA_NOME);
        setCampi(jLabelCampo3, txNomeCampo3);
        txNomeCampo3.setText(InfermiereMySqlDAO.NOME_COLONNA_COGNOME);
        unsetCampi(jLabelCampo4, txNomeCampo4);
        unsetCampi(jLabelCampo5, txNomeCampo5);
        unsetCampi(jLabelCampo6, txNomeCampo6);
        unsetCampi(jLabelCampo7, txNomeCampo7);
        unsetCampi(jLabelCampo8, txNomeCampo8);
        unsetCampi(jLabelCampo9, txNomeCampo9);
        unsetCampi(jLabelCampo10, txNomeCampo10);
    }
        
    private void buttonTabInterventiActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        tabella = tabella.interventi;
        formInterventi();
    }                                                   

    private void formInterventi(){
        setCampi(jLabelTabella, txNomeTabella);
        setCampi(jLabelCampo1, txNomeCampo1);
        setCampi(jLabelCampo2, txNomeCampo2);
        txNomeTabella.setText(InterventoMySqlDAO.NOME_TABELLA_INTERVENTI);
        txNomeCampo1.setText(InterventoMySqlDAO.NOME_COLONNA_ID);
        txNomeCampo2.setText(InterventoMySqlDAO.NOME_COLONNA_ID_PAZIENTE);
        setCampi(jLabelCampo3, txNomeCampo3);
        setCampi(jLabelCampo4, txNomeCampo4);
        setCampi(jLabelCampo5, txNomeCampo5);
        setCampi(jLabelCampo6, txNomeCampo6);
        setCampi(jLabelCampo7, txNomeCampo7);
        setCampi(jLabelCampo8, txNomeCampo8);
        setCampi(jLabelCampo9, txNomeCampo9);
        setCampi(jLabelCampo10, txNomeCampo10);
        txNomeCampo3.setText(InterventoMySqlDAO.NOME_COLONNA_ID_INFERMIERE);
        txNomeCampo4.setText(InterventoMySqlDAO.NOME_COLONNA_CITTA);
        txNomeCampo5.setText(InterventoMySqlDAO.NOME_COLONNA_CIVICO);
        txNomeCampo6.setText(InterventoMySqlDAO.NOME_COLONNA_CAP);
        txNomeCampo7.setText(InterventoMySqlDAO.NOME_COLONNA_DATA);
        txNomeCampo8.setText(InterventoMySqlDAO.NOME_COLONNA_ORA_INIZIO);
        txNomeCampo9.setText(InterventoMySqlDAO.NOME_COLONNA_ORA_FINE);
        txNomeCampo10.setText(InterventoMySqlDAO.NOME_COLONNA_STORICO);
    }
    
    private void buttonTabTipiInterventoActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        tabella = tabella.tipiInterventi;
        formTipiIntervento();
    }                                                       

    private void formTipiIntervento(){
        setCampi(jLabelTabella, txNomeTabella);
        setCampi(jLabelCampo1, txNomeCampo1);
        setCampi(jLabelCampo2, txNomeCampo2);
        txNomeTabella.setText(InterventoMySqlDAO.NOME_TABELLA_TIPI_INTERVENTI);
        txNomeCampo1.setText(InterventoMySqlDAO.NOME_COLONNA_ID_TIPO_INTERVENTO);
        txNomeCampo2.setText(InterventoMySqlDAO.NOME_COLONNA_IDINT_TIPO);
        setCampi(jLabelCampo3, txNomeCampo3);
        setCampi(jLabelCampo4, txNomeCampo4);
        setCampi(jLabelCampo5, txNomeCampo5);
        setCampi(jLabelCampo6, txNomeCampo6);
        txNomeCampo3.setText(InterventoMySqlDAO.NOME_COLONNA_NOME_TIPO);
        txNomeCampo4.setText(InterventoMySqlDAO.NOME_COLONNA_VALORE_RILEVATO);
        txNomeCampo5.setText(InterventoMySqlDAO.NOME_COLONNA_TEMPO_INTERVENTO);
        txNomeCampo6.setText(InterventoMySqlDAO.NOME_COLONNA_NOTE_TIPO);
        unsetCampi(jLabelCampo7, txNomeCampo7);
        unsetCampi(jLabelCampo8, txNomeCampo8);
        unsetCampi(jLabelCampo9, txNomeCampo9);
        unsetCampi(jLabelCampo10, txNomeCampo10);
    }
    
    private void buttonTabPatologieTipiInterventoActionPerformed(java.awt.event.ActionEvent evt) {                                                                 
        tabella = tabella.patologieTipiInterventi;
        formPatologieTipiIntervento();
    }                                                                

    private void formPatologieTipiIntervento(){
        setCampi(jLabelTabella, txNomeTabella);
        setCampi(jLabelCampo1, txNomeCampo1);
        setCampi(jLabelCampo2, txNomeCampo2);
        txNomeTabella.setText(InterventoMySqlDAO.NOME_TABELLA_PATOLOGIE_TIPI_INTERVENTI);
        txNomeCampo1.setText(InterventoMySqlDAO.NOME_COLONNA_ID_PAT_INTERVENTO);
        txNomeCampo2.setText(InterventoMySqlDAO.NOME_COLONNA_ID_TIPO_INTERVENTO_PATOLOGIE_TIPI_INTERVENTI);
        txNomeCampo3.setText(InterventoMySqlDAO.NOME_COLONNA_ID_PATOLOGIA_PATOLOGIE_TIPI_INTERVENTI);
        setCampi(jLabelCampo3, txNomeCampo3);
        setCampi(jLabelCampo4, txNomeCampo4);
        txNomeCampo4.setText(InterventoMySqlDAO.NOME_COLONNA_GRAVITA_PATOLOGIE_TIPI_INTERVENTI); 
        unsetCampi(jLabelCampo5, txNomeCampo5);
        unsetCampi(jLabelCampo6, txNomeCampo6);
        unsetCampi(jLabelCampo7, txNomeCampo7);
        unsetCampi(jLabelCampo8, txNomeCampo8);
        unsetCampi(jLabelCampo9, txNomeCampo9);
        unsetCampi(jLabelCampo10, txNomeCampo10);
    }
    
    private void formPatologie(){
        setCampi(jLabelTabella, txNomeTabella);
        setCampi(jLabelCampo1, txNomeCampo1);
        setCampi(jLabelCampo2, txNomeCampo2);
        txNomeTabella.setText(PatologiaMySqlDAO.NOME_TABELLA);
        txNomeCampo1.setText(PatologiaMySqlDAO.NOME_COLONNA_ID);
        txNomeCampo2.setText(PatologiaMySqlDAO.NOME_COLONNA_CODICE);
        setCampi(jLabelCampo3, txNomeCampo3);
        txNomeCampo3.setText(PatologiaMySqlDAO.NOME_COLONNA_NOME);
        unsetCampi(jLabelCampo4, txNomeCampo4);
        unsetCampi(jLabelCampo5, txNomeCampo5);
        unsetCampi(jLabelCampo6, txNomeCampo6);
        unsetCampi(jLabelCampo7, txNomeCampo7);
        unsetCampi(jLabelCampo8, txNomeCampo8);
        unsetCampi(jLabelCampo9, txNomeCampo9);
        unsetCampi(jLabelCampo10, txNomeCampo10);
    }
    
    private void pulsanteHome3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(GMessage.confirm(editorDatabase.getString("SEI SICURO DI VOLER ABBANDONARE")
            + editorDatabase.getString(" ADISYS?")) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }                                             

  
                    

    private void buttonTabPatologieActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        tabella = tabella.patologie;
        formPatologie();
    }                                                  

    private void buttonTabPazientiActionPerformed(java.awt.event.ActionEvent evt) {                                                  

        tabella = Tabella.pazienti;
        formPazienti();

    }                                                 

    private void pulsanteResettaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        if(tabella == tabella.infermieri)
        formInfermieri();
        if(tabella == tabella.pazienti)
        formPazienti();
        if(tabella == tabella.cellulari)
        formCellulari();
        if(tabella == tabella.interventi)
        formInterventi();
        if(tabella == tabella.tipiInterventi)
        formTipiIntervento();
        if(tabella == tabella.patologieTipiInterventi)
        formInfermieri();
        if(tabella == tabella.patologie)
        formPatologie();
    }                                               

    private void pulsanteOKActionPerformed(java.awt.event.ActionEvent evt) {                                           
        boolean error = false;
       if (txNomeTabella.getText().equals("") || txNomeCampo1.getText().equals("") || txNomeCampo2.getText().equals(""))
           error = true;
       if ((tabella == tabella.infermieri || tabella == tabella.patologie || tabella == tabella.patologieTipiInterventi) &&
           txNomeCampo3.getText().equals(""))
           error = true;
       if (tabella == tabella.pazienti && (
           txNomeCampo3.getText().equals("") || txNomeCampo4.getText().equals("")))
           error = true;
       if (tabella == tabella.tipiInterventi && (
           txNomeCampo3.getText().equals("") || txNomeCampo4.getText().equals("") || txNomeCampo5.getText().equals("") || txNomeCampo6.getText().equals("")))
           error = true;
       if (tabella == tabella.interventi && (
           txNomeCampo3.getText().equals("") || txNomeCampo4.getText().equals("") || txNomeCampo5.getText().equals("") || txNomeCampo7.getText().equals("") || txNomeCampo7.getText().equals("") || txNomeCampo8.getText().equals("") || txNomeCampo9.getText().equals("")))
           error = true;
       if (error == true){
           GMessage.message_error(editorDatabase.getString("SONO STATI RILEVATI CAMPI VUOTI. RIVEDERE IL FORM."));
           pulsanteResettaActionPerformed(null);
       } else {
           String messaggio = editorDatabase.getString("SEI SICURO DI VOLER MODIFICARE LA TABELLA") 
                    + " " + tabella + "?";
           if (GMessage.confirm(messaggio) == JOptionPane.YES_OPTION) {
               boolean ok = true;
               FC = RequestManager.getFCInstance();
               if (tabella == tabella.infermieri) {
                   ArrayList < String > listaCampi = new ArrayList();
                   listaCampi.add(txNomeTabella.getText());
                   listaCampi.add(txNomeCampo1.getText());
                   listaCampi.add(txNomeCampo2.getText());
                   listaCampi.add(txNomeCampo3.getText());
                   ArrayList < Record < String, Object >> params = new ArrayList < Record < String, Object >> ();
                   params.add(new Record < String, Object > ("java.util.ArrayList", listaCampi));
                   try {
                       ok = (boolean) FC.processRequest("modificaTabellaInfermieri", params);
                   } catch (MainException ex) {
                       Logger.getLogger(EditorDatabase.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
               if (tabella == tabella.pazienti) {
                   ArrayList < String > listaCampi = new ArrayList();
                   listaCampi.add(txNomeTabella.getText());
                   listaCampi.add(txNomeCampo1.getText());
                   listaCampi.add(txNomeCampo2.getText());
                   listaCampi.add(txNomeCampo3.getText());
                   listaCampi.add(txNomeCampo4.getText());
                   ArrayList < Record < String, Object >> params = new ArrayList < Record < String, Object >> ();
                   params.add(new Record < String, Object > ("java.util.ArrayList", listaCampi));
                   try {
                       ok = (boolean) FC.processRequest("modificaTabellaPazienti", params);
                   } catch (MainException ex) {
                       Logger.getLogger(EditorDatabase.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
               if (tabella == tabella.patologie) {
                   ArrayList < String > listaCampi = new ArrayList();
                   listaCampi.add(txNomeTabella.getText());
                   listaCampi.add(txNomeCampo1.getText());
                   listaCampi.add(txNomeCampo2.getText());
                   listaCampi.add(txNomeCampo3.getText());
                   ArrayList < Record < String, Object >> params = new ArrayList < Record < String, Object >> ();
                   params.add(new Record < String, Object > ("java.util.ArrayList", listaCampi));
                   try {
                       ok = (boolean) FC.processRequest("modificaTabellaPatologie", params);
                   } catch (MainException ex) {
                       Logger.getLogger(EditorDatabase.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
               if (tabella == tabella.tipiInterventi) {
                   ArrayList < String > listaCampi = new ArrayList();
                   listaCampi.add(txNomeTabella.getText());
                   listaCampi.add(txNomeCampo1.getText());
                   listaCampi.add(txNomeCampo2.getText());
                   listaCampi.add(txNomeCampo3.getText());
                   listaCampi.add(txNomeCampo4.getText());
                   listaCampi.add(txNomeCampo5.getText());
                   listaCampi.add(txNomeCampo6.getText());

                   ArrayList < Record < String, Object >> params = new ArrayList < Record < String, Object >> ();
                   params.add(new Record < String, Object > ("java.util.ArrayList", listaCampi));
                   try {
                       ok = (boolean) FC.processRequest("modificaTabellaTipiIntervento", params);
                   } catch (MainException ex) {
                       Logger.getLogger(EditorDatabase.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
               if (tabella == tabella.interventi) {
                   ArrayList < String > listaCampi = new ArrayList();
                   listaCampi.add(txNomeTabella.getText());
                   listaCampi.add(txNomeCampo1.getText());
                   listaCampi.add(txNomeCampo2.getText());
                   listaCampi.add(txNomeCampo3.getText());
                   listaCampi.add(txNomeCampo4.getText());
                   listaCampi.add(txNomeCampo5.getText());
                   listaCampi.add(txNomeCampo6.getText());
                   listaCampi.add(txNomeCampo7.getText());
                   listaCampi.add(txNomeCampo8.getText());
                   listaCampi.add(txNomeCampo9.getText());
                   listaCampi.add(txNomeCampo10.getText());
                   ArrayList < Record < String, Object >> params = new ArrayList < Record < String, Object >> ();
                   params.add(new Record < String, Object > ("java.util.ArrayList", listaCampi));
                   try {
                       ok = (boolean) FC.processRequest("modificaTabellaInterventi", params);
                   } catch (MainException ex) {
                       Logger.getLogger(EditorDatabase.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
               if (tabella == tabella.cellulari) {
                   ArrayList < String > listaCampi = new ArrayList();
                   listaCampi.add(txNomeTabella.getText());
                   listaCampi.add(txNomeCampo1.getText());
                   listaCampi.add(txNomeCampo2.getText());
                   ArrayList < Record < String, Object >> params = new ArrayList < Record < String, Object >> ();
                   params.add(new Record < String, Object > ("java.util.ArrayList", listaCampi));
                   try {
                       ok = (boolean) FC.processRequest("modificaTabellaCellulari", params);
                   } catch (MainException ex) {
                       Logger.getLogger(EditorDatabase.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
               if (tabella == tabella.patologieTipiInterventi) {
                   ArrayList < String > listaCampi = new ArrayList();
                   listaCampi.add(txNomeTabella.getText());
                   listaCampi.add(txNomeCampo1.getText());
                   listaCampi.add(txNomeCampo2.getText());
                   listaCampi.add(txNomeCampo3.getText());
                   listaCampi.add(txNomeCampo4.getText());
                   ArrayList < Record < String, Object >> params = new ArrayList < Record < String, Object >> ();
                   params.add(new Record < String, Object > ("java.util.ArrayList", listaCampi));
                   try {
                       ok = (boolean) FC.processRequest("modificaTabellaPatologieIntervento", params);
                   } catch (MainException ex) {
                       Logger.getLogger(EditorDatabase.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
                 if(ok == true)
                           GMessage.information(editorDatabase.getString("TABELLA") + tabella + 
                                   editorDatabase.getString("MODIFICATA CON SUCCESSO"));
                 else
                     pulsanteResettaActionPerformed(null);
           } //if su risposta si joption pane

       }
    }                                          

                                          

    private void txNomeCampo9ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void request(String request){
        FC = RequestManager.getFCInstance();
        if(FC.processRequest(request)){
            System.out.println("Finestra " + request + " aperta con successo.");
        }
        else{
            messaggistica.GMessage.winNotFound(request);
        }
    }
        
	/**
	 *
	 */
	public static void start() {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if (editorDatabase.getString("NIMBUS").equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditorDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditorDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditorDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditorDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				EditorDatabase window = new EditorDatabase();
				Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit().getScreenSize();
				window.setLocation(new Point( (risoluzioneSchermo.width - window.getWidth()) /2, (risoluzioneSchermo.height - window.getHeight()) /2)  );
				window.setVisible(true);

			}
		});

	}

    // Variables declaration - do not modify                     
    private javax.swing.JMenuBar barraDeiMenu;
    private javax.swing.JButton buttonTabCellulariPazienti;
    private javax.swing.JButton buttonTabInfermieri;
    private javax.swing.JButton buttonTabInterventi;
    private javax.swing.JButton buttonTabPatologie;
    private javax.swing.JButton buttonTabPatologieTipiIntervento;
    private javax.swing.JButton buttonTabPazienti;
    private javax.swing.JButton buttonTabTipiIntervento;
    private javax.swing.JLabel intestazione;
    private javax.swing.JLabel jLabelCampo1;
    private javax.swing.JLabel jLabelCampo10;
    private javax.swing.JLabel jLabelCampo2;
    private javax.swing.JLabel jLabelCampo3;
    private javax.swing.JLabel jLabelCampo4;
    private javax.swing.JLabel jLabelCampo5;
    private javax.swing.JLabel jLabelCampo6;
    private javax.swing.JLabel jLabelCampo7;
    private javax.swing.JLabel jLabelCampo8;
    private javax.swing.JLabel jLabelCampo9;
    private javax.swing.JLabel jLabelTabella;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pulsanteHome3;
    private javax.swing.JButton pulsanteIndietro;
    private javax.swing.JButton pulsanteOK;
    private javax.swing.JButton pulsanteResetta;
    private javax.swing.JButton pulsanteServer;
    private javax.swing.JTextArea txInfoData;
    private javax.swing.JTextField txNomeCampo1;
    private javax.swing.JTextField txNomeCampo10;
    private javax.swing.JTextField txNomeCampo2;
    private javax.swing.JTextField txNomeCampo3;
    private javax.swing.JTextField txNomeCampo4;
    private javax.swing.JTextField txNomeCampo5;
    private javax.swing.JTextField txNomeCampo6;
    private javax.swing.JTextField txNomeCampo7;
    private javax.swing.JTextField txNomeCampo8;
    private javax.swing.JTextField txNomeCampo9;
    private javax.swing.JTextField txNomeTabella;
    // End of variables declaration                   

    @Override
    public void open() {
        start();
    }

    private enum Tabella{pazienti,
                        cellulari,
                        infermieri, 
                        interventi, 
                        tipiInterventi,
                        patologieTipiInterventi,
                        patologie};
    private Tabella tabella;

}
