/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adisys.server.boundary;

import adisys.server.strumenti.VariableTableModel;
import business.patologia.PatologiaTO;
import messaggistica.MainException;
import integration.dao.PatologiaMySqlDAO;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;
import presentation.FrontController;
import presentation.RequestManager;
import adisys.server.strumenti.Record;
import messaggistica.GMessage;

/**
/**
 *
 * @author Luca
 */
public class EditorPatologie extends javax.swing.JDialog implements Boundary {
    private FrontController FC;
    private static ResourceBundle editorPatologie = ResourceBundle.getBundle("adisys/server/property/EditorPatologie");
    private static final int LUNGHEZZAMASSIMACODICE = 6;
    private static final int LUNGHEZZAMASSIMANOME = 20;

    public static void setResourceBundle(String path, Locale locale){
        editorPatologie = ResourceBundle.getBundle(path, locale);
    }
    /**
     * Creates new form EditorPatologie3
     */
    public EditorPatologie(java.awt.Frame parent, boolean modal) throws MainException {
        super(parent, modal);
		initComponents();
		aggiornaTabella();
		//codFormat();
		setAggiungiPatologia();
    }
    
    public EditorPatologie(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        immagineTestataPatologie = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pulsanteCancella = new javax.swing.JButton();
        pulsanteModifica = new javax.swing.JButton();
        pulsanteAggiungi = new javax.swing.JButton();
        pulsanteCancellaTutti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txInfo = new javax.swing.JTextArea();
        pannelloModifica = new javax.swing.JPanel();
        txNome = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pulsanteOK = new javax.swing.JButton();
        txID = new javax.swing.JFormattedTextField();
        pulsanteHome = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabellaPatologie = new javax.swing.JTable();
        txModalita = new javax.swing.JTextField();
        txPatologiaSelezionata = new javax.swing.JFormattedTextField();
        pulsanteEsci = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(editorPatologie.getString("TITLE")); // NOI18N
        setMinimumSize(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        immagineTestataPatologie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/decorazioniFinestre/Patologia.png"))); // NOI18N

        pulsanteCancella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaCancella.png"))); // NOI18N
        pulsanteCancella.setText(editorPatologie.getString("CANCELLA PATOLOGIA")); // NOI18N
        pulsanteCancella.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteCancellaActionPerformed(evt);
            }
        });

        pulsanteModifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaModifica.png"))); // NOI18N
        pulsanteModifica.setText(editorPatologie.getString("MODIFICA PATOLOGIA")); // NOI18N
        pulsanteModifica.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteModificaActionPerformed(evt);
            }
        });

        pulsanteAggiungi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaAggiungi.png"))); // NOI18N
        pulsanteAggiungi.setText(editorPatologie.getString("AGGIUNGI PATOLOGIA")); // NOI18N
        pulsanteAggiungi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteAggiungiActionPerformed(evt);
            }
        });

        pulsanteCancellaTutti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaCancellaTutti.png"))); // NOI18N
        pulsanteCancellaTutti.setText(editorPatologie.getString("CANCELLA TUTTE LE PATOLOGIE")); // NOI18N
        pulsanteCancellaTutti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteCancellaTutti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteCancellaTuttiActionPerformed(evt);
            }
        });

        txInfo.setEditable(false);
        txInfo.setBackground(new java.awt.Color(240, 240, 240));
        txInfo.setLineWrap(true);
        txInfo.setText(editorPatologie.getString("INSERIRE I DATI DELLA PATOLOGIA E PREMERE OK")); // NOI18N
        jScrollPane1.setViewportView(txInfo);

        jLabel21.setText(editorPatologie.getString("NOME PATOLOGIA")); // NOI18N

        jLabel23.setText(editorPatologie.getString("CODICE PATOLOGIA")); // NOI18N

        pulsanteOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/iconainseriscirossa.png"))); // NOI18N
        pulsanteOK.setText(editorPatologie.getString("OK")); // NOI18N
        pulsanteOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteOKActionPerformed(evt);
            }
        });

        txID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("000000"))));

        pulsanteHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/home.png"))); // NOI18N
        pulsanteHome.setText(editorPatologie.getString("HOME")); // NOI18N
        pulsanteHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannelloModificaLayout = new javax.swing.GroupLayout(pannelloModifica);
        pannelloModifica.setLayout(pannelloModificaLayout);
        pannelloModificaLayout.setHorizontalGroup(
            pannelloModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloModificaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pannelloModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelloModificaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pulsanteHome))
                    .addComponent(pulsanteOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pannelloModificaLayout.createSequentialGroup()
                        .addGroup(pannelloModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)
                            .addComponent(txNome, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txID))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pannelloModificaLayout.setVerticalGroup(
            pannelloModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloModificaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pulsanteOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsanteHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(pannelloModifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(pulsanteCancellaTutti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pulsanteCancella, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pulsanteModifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pulsanteAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pulsanteAggiungi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsanteModifica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsanteCancella)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsanteCancellaTutti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelloModifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabellaPatologie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tabellaPatologie);

        txModalita.setEditable(false);
        txModalita.setText(editorPatologie.getString("OPERAZIONE")); // NOI18N

        txPatologiaSelezionata.setEditable(false);
        txPatologiaSelezionata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        pulsanteEsci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/arresta.png"))); // NOI18N
        pulsanteEsci.setText(editorPatologie.getString("ABBANDONA ADISYS")); // NOI18N
        pulsanteEsci.setToolTipText(editorPatologie.getString("ESCI DA ADISYS")); // NOI18N
        pulsanteEsci.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEsciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(immagineTestataPatologie)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pulsanteEsci))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txModalita, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPatologiaSelezionata, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(immagineTestataPatologie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txModalita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txPatologiaSelezionata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pulsanteEsci)
                        .addGap(12, 12, 12))))
        );

        pack();
    }// </editor-fold>                        
 
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        if(GMessage.confirm(editorPatologie.getString("SEI SICURO DI VOLER USCIRE DALL'")
                 + editorPatologie.getString("EDITOR DELLE PATOLOGIE?"))   
                 == JOptionPane.YES_OPTION) {
             this.dispose();
         }
    }                                  

    private void pulsanteEsciActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(GMessage.confirm(editorPatologie.getString("SEI SICURO DI VOLER ABBANDONARE")
            + editorPatologie.getString(" ADISYS?")) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }                                            

    private void pulsanteCancellaTuttiActionPerformed(java.awt.event.ActionEvent evt) {                                                      
       String messaggio = editorPatologie.getString("CONFERMARE LA CANCELLAZIONE DI TUTTE LE PATOLOGIE?L'OPERAZIONE NON POTRA' ESSERE ANNULLATA.")
                        + editorPatologie.getString("E' POSSIBILE CHE NON TUTTE LE PATOLOGIE VENGANO CANCELLATE IN QUANTO ASSOCIATE AD INTERVENTI");

		if (GMessage.confirm(messaggio) == JOptionPane.YES_OPTION){
                System.out.println("Evento pulsante CancellaTuttePatologie");
                try {
                    if((Boolean) FC.processRequest("cancellaTuttePatologie", null)) {
                        System.out.println("Cancellazione di tutte le patologie avvenuta con successo");
                            
                        messaggio = editorPatologie.getString("CANCELLAZIONE AVVENUTA CON SUCCESSO");
                            /*messaggio = editorPatologie.getString("NON E' STATA RIMOSSA ALCUNA PATOLOGIA"
                                    + " IN QUANTO ASSOCIATE TUTTE AD INTERVENTI");*/
                        GMessage.information(messaggio);
                        aggiornaTabella();
                    } else {
                           messaggio = editorPatologie.getString("NON E' STATA RIMOSSA ALCUNA PATOLOGIA"
                                    + " IN QUANTO ASSOCIATE TUTTE AD INTERVENTI");
                           GMessage.information(messaggio);
                        //GMessage.message_error(editorPatologie.getString("CANCTUTTI"));
                    }
                } catch (MainException ex) {
                    Logger.getLogger(EditorPatologie.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }                                                     

    private void pulsanteAggiungiActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        setAggiungiPatologia();
    }                                                

    private void pulsanteModificaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        setModificaPatologia();
    }                                                

    private void pulsanteCancellaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if(tabellaPatologie.getSelectedRow()==-1)
            GMessage.message_error(editorPatologie.getString("SELEZIONARE LA PATOLOGIA DA CANCELLARE E POI PREMERE IL PULSANTE CANCELLA PATOLOGIA"));
        else
        {
            if(GMessage.confirm(editorPatologie.getString(
                    "SEI SICURO DI VOLER CANCELLARE LA PATOLOGIA SELEZIONATA?"))
                    == JOptionPane.YES_OPTION) {
          
                //Recupero Codice
                Object id = tabellaPatologie.getValueAt(tabellaPatologie.getSelectedRow(),
                        tabellaPatologie.getColumnModel().getColumnIndex(PatologiaMySqlDAO.NOME_COLONNA_ID));

                //Casting Codice
                int idInt=Integer.valueOf(String.valueOf(id));
                
                String nome = tabellaPatologie.getValueAt(tabellaPatologie.getSelectedRow(),
                    tabellaPatologie.getColumnModel().getColumnIndex(PatologiaMySqlDAO.NOME_COLONNA_NOME)).toString();
                String codice = tabellaPatologie.getValueAt(tabellaPatologie.getSelectedRow(),
                    tabellaPatologie.getColumnModel().getColumnIndex(PatologiaMySqlDAO.NOME_COLONNA_CODICE)).toString();
                
                        //TODO Caricamento numeri di cellulare
                        PatologiaTO to = new PatologiaTO();
                        
                        to.setID(idInt);
                        to.setCodice(codice);
                        to.setNome(nome);
                        ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
                        params.add(new Record<String, Object>("business.patologia.PatologiaTO", to));
                        //Caso no ID -> NUOVO PAZIENTE: effettua l'inserimento
                        ResultSet patAssociate = null;
                        try {
                            patAssociate = (ResultSet) FC.processRequest(
                                    "visualizzaPatologieAssociate", params);
                        } catch (MainException ex) {
                                Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
                        }
      
                //Trasfermento dati (se la tabella non è vuota)
                try {
                    if(patAssociate.first())
                    {
                        GMessage.message_error(editorPatologie.getString("IMPOSSIBILE ELIMINARE LA PATOLOGIA")
                            + editorPatologie.getString(" SELEZIONATA IN QUANTO ASSOCIATA AD INTERVENTI"));
                        return;
                    }
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                    //trace

                }
                //Cancellazione
              //Casting ID
            
            System.out.println("Evento pulsante CancellaPatologia : "+ to);
            params.clear();
            params.add(new Record<String, Object>("business.patologia.PatologiaTO", to));
            try {
                if((Boolean) FC.processRequest("cancellaPatologia", params)){
                    System.out.println("Cancellazione della patologia eseguita con successo");
                    String messaggio = java.text.MessageFormat.format(editorPatologie.getString("PATOLOGIA: {0} "), 
                            new Object[] {to.getCodice().toUpperCase()}) + " " + to.getNome().toUpperCase() + 
                            editorPatologie.getString("CANCELLATA CON SUCCESSO!");
                    GMessage.information(messaggio);
                }
                else{
                    GMessage.message_error(editorPatologie.getString("CANCPATOLOGIA"));
                }
            } catch (MainException ex) {
                Logger.getLogger(EditorPatologie.class.getName()).log(Level.SEVERE, null, ex);
            }
	
            try {
                //Aggiornamento tabella
                aggiornaTabella();
            } catch (MainException ex) {
                Logger.getLogger(EditorPatologie.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }                                                

    private void pulsanteHomeActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(GMessage.confirm(editorPatologie.getString("SEI SICURO DI VOLER USCIRE DALL'")
            + editorPatologie.getString("EDITOR DELLE PATOLOGIE E TORNARE ALLA HOME?"))
        == JOptionPane.YES_OPTION) {
        this.dispose();
        }
    }                                            

    private void pulsanteOKActionPerformed(java.awt.event.ActionEvent evt) {                                           
       
        //Aggiunta paziente
        rigaSelezionata = -1;
        if (modalita == Modalita.aggiungi) {
            if(datiValidi()){
                if(GMessage.confirm(editorPatologie.getString("CREARE NUOVA PATOLOGIA")) == 
                       JOptionPane.YES_OPTION){
                    PatologiaTO to;
                    try {
                        to = getValueJustInsert();
                        ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
                        params.add(new Record<String, Object>("business.patologia.PatologiaTO", to));
                        try {
                            boolean ok = (boolean) FC.processRequest("creaPatologia", params);
                            if(ok){
                                //Aggiunta al database
                                String messaggio = java.text.MessageFormat.format(editorPatologie.getString("PATOLOGIA: {0} "), new Object[] {
                                to.getCodice().toUpperCase()}) + " " + to.getNome().toUpperCase() + editorPatologie.getString("CREATA CON SUCCESSO!");
                                GMessage.information(messaggio);
                                setAggiungiPatologia();
                            } else {
                                //Caso patologia non aggiunto
                                String messaggio= editorPatologie.getString("SI È VERIFICATO UN ERRORE, IMPOSSIBILE CREARE LA PATOLOGIA");
                                GMessage.message_error(messaggio);
                            }
                        } catch (MainException ex) {
                            Logger.getLogger(EditorPatologie.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (ParseException ex) {
                        Logger.getLogger(EditorPatologie.class.getName()).log(Level.SEVERE, null, ex);
                    }		
                }
            }
        } else if (modalita == Modalita.modifica) {
                rigaSelezionata = tabellaPatologie.getSelectedRow();
        if(datiValidi()){
            if(GMessage.confirm(editorPatologie.getString("SEI SICURO DI MODIFICARE")) == 
                    JOptionPane.YES_OPTION){
                PatologiaTO to;
                try {
                    to = getValueJustUpdate();
                    ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
                    params.add(new Record<String, Object>("business.patologia.PatologiaTO", to));
                    try {
                        boolean ok = (boolean) FC.processRequest("modificaPatologia", params);
                        if(ok){
                            //Aggiunta al database
                            String messaggio = java.text.MessageFormat.format(editorPatologie.getString("PATOLOGIA: {0} "), new Object[] {
                                    tabellaPatologie.getValueAt(rigaSelezionata,
                                    tabellaPatologie.getColumnModel().getColumnIndex(PatologiaMySqlDAO.NOME_COLONNA_CODICE)).
                                    toString().toUpperCase()}) 
                                    + " " + tabellaPatologie.getValueAt(rigaSelezionata,
                                    tabellaPatologie.getColumnModel().getColumnIndex(PatologiaMySqlDAO.NOME_COLONNA_NOME)).
                                    toString().toUpperCase(); 
                                    messaggio = messaggio + editorPatologie.getString("MODIFICATA IN:") +
                                    to.getCodice() + " " + to.getNome().toUpperCase() + editorPatologie.getString("CON SUCCESSO!");
                                    GMessage.information(messaggio);
                                    setAggiungiPatologia();
                                    aggiornaTabella();
			}
			else
			{
				//Caso patologia non aggiunto
				String messaggio= editorPatologie.getString("SI È VERIFICATO UN ERRORE, IMPOSSIBILE MODIFICARE L'INFERMIERE");
				GMessage.message_error(messaggio);
			}
                    } catch (MainException ex) {
                        Logger.getLogger(EditorPatologie.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(EditorPatologie.class.getName()).log(Level.SEVERE, null, ex);
                }
						
              }//if su dati validi
         }//if su joptione
        }
        try {
            //Aggiornamento tabella
            aggiornaTabella();
        } catch (MainException ex) {
            Logger.getLogger(EditorPatologie.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }                                          

    /**
	 * Restituisce i valori dei campi appena inseriti
	 * @return una struttura dati di String con i valori appena inseriti
	 * @throws ParseException 
	*/
	private PatologiaTO getValueJustInsert() throws ParseException{
		
		PatologiaTO to = new PatologiaTO(txID.getText(), txNome.getText().toUpperCase());
		System.out.println(to);
		
		return to;
		
	}
        
        /**
	 * Restituisce i valori dei campi appena inseriti
	 * @return una struttura dati di String con i valori appena inseriti
	 * @throws ParseException 
	*/
	private PatologiaTO getValueJustUpdate() throws ParseException{
	
                Object id = tabellaPatologie.getValueAt(tabellaPatologie.getSelectedRow(),
                        tabellaPatologie.getColumnModel().getColumnIndex(PatologiaMySqlDAO.NOME_COLONNA_ID));
                String codice = txID.getText();
		PatologiaTO to = new PatologiaTO(Integer.parseInt(id.toString()), codice,  txNome.getText());
		System.out.println(to);
		
		return to;
		
	}
	
   private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        try {
            aggiornaTabella();
        } catch (MainException ex) {
            Logger.getLogger(EditorPatologie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
    
      public void aggiornaTabella() throws MainException
	{
		FC = RequestManager.getFCInstance();
		AbstractTableModel modelAdisys = (AbstractTableModel) FC.processRequest("visualizzaPatologie", null);
		tabellaPatologie.setModel(modelAdisys);
                if(tabellaPatologie.getRowCount() == 0){
                    VariableTableModel modello = new VariableTableModel();
                    modello.addColumn("");
                     String[] msg = {editorPatologie.getString("NON È STATA TROVATA ALCUNA PATOLOGIA REGISTRATA NEL")
                        + editorPatologie.getString(" SISTEMA.")};
                     modello.addRow(msg);
                     tabellaPatologie.setModel(modello);
                     pulsanteModifica.setVisible(false);
                     pulsanteCancella.setVisible(false);
                     pulsanteCancellaTutti.setVisible(false);
                     return;
                }
		TableColumn col = tabellaPatologie.getColumnModel().getColumn(
                        tabellaPatologie.getColumnModel().getColumnIndex(PatologiaMySqlDAO.NOME_COLONNA_ID));
				col.setMinWidth(0);
				col.setMaxWidth(0);
				col.setPreferredWidth(0);
                 if(pulsanteModifica.isVisible() == false){
                     pulsanteModifica.setVisible(true);
                     pulsanteCancella.setVisible(true);
                     pulsanteCancellaTutti.setVisible(true);
                 }
		if(rigaSelezionata != -1)
                    tabellaPatologie.setRowSelectionInterval(rigaSelezionata, rigaSelezionata);
	}


	public boolean datiValidi()
	{
		String messaggio =editorPatologie.getString("ATTENZIONE");
		int errori=0;
		if (txID.getText().isEmpty())
		{
			errori++;
			messaggio += editorPatologie.getString("CODICE PATOLOGIA VUOTO");
		} else if(txID.getText().length() > LUNGHEZZAMASSIMACODICE){
                        errori++;
			messaggio += editorPatologie.getString("CODICE PATOLOGIA TROPPO LUNGO (MAX");
                        messaggio += LUNGHEZZAMASSIMACODICE + " ";
                        messaggio += editorPatologie.getString("CAR)");
                } else {
                    int numRows = tabellaPatologie.getRowCount();
                    for(int i = 0; i < numRows; i++){
                        int colonnaCodice = tabellaPatologie.getColumnModel().getColumnIndex(PatologiaMySqlDAO.NOME_COLONNA_CODICE);
                        int colonnaNome = tabellaPatologie.getColumnModel().getColumnIndex(PatologiaMySqlDAO.NOME_COLONNA_NOME);
                        if(txID.getText().equals(tabellaPatologie.getValueAt(i, colonnaCodice)) && i != tabellaPatologie.getSelectedRow()){
                            errori++;
                            messaggio += java.text.MessageFormat.format(editorPatologie.getString("CODICE {0} GIÀ PRESENTE") + 
                                    " (" + tabellaPatologie.getValueAt(i, colonnaNome) + ") ", new Object[] {txID.getText()});
                            break;
                }//if
            }//for
                }
                 
		if(txNome.getText().isEmpty())
		{
			errori++;
			messaggio += editorPatologie.getString("NOME PATOLOGIA VUOTO");
		} else if(txNome.getText().length() > LUNGHEZZAMASSIMANOME){
                        errori++;
			messaggio += editorPatologie.getString("NOME PATOLOGIA TROPPO LUNGO (MAX");
                        messaggio += LUNGHEZZAMASSIMANOME + " ";
                        messaggio += editorPatologie.getString("CAR)");
                } 
                                boolean numeric = false;
                for(int i = 0; i < txNome.getText().length(); i++){
                    if(txNome.getText().toCharArray()[i] >= '0' && txNome.getText().toCharArray()[i] <= '9'){
                        numeric = true;
                        break;
                    }
                }
                if(numeric == true){
                        errori++;
			messaggio += editorPatologie.getString("IL NOME DELLA PATOLOGIA CONTIENE CARATTERI NUMERICI");
                }
		if (errori==0) return true;
		else 
		{
			messaggio+= editorPatologie.getString("\n")+String.valueOf(errori)+editorPatologie.getString(" ERRORI RILEVATI.");
			GMessage.message_error(messaggio);
			return false;
		}

	}

	private void setAggiungiPatologia()
	{
		//Setta la variabile modalita
		modalita=Modalita.aggiungi;
                txModalita.setText(modAggiungi);
                txPatologiaSelezionata.setText("");
		//Setta il modulo per l'inserimento
		txID.setText("");
		txNome.setText("");
		
		txInfo.setText(editorPatologie.getString("AGGIUNGI UNA NUOVA PATOLOGIA INSERIRE UN CODICE DI MAX 6 CIFRE UNIVOCO")
                        + editorPatologie.getString(", UN NOME E PREMERE OK"));
	}

	private void setModificaPatologia()
	{

		if(tabellaPatologie.getSelectedRow()==-1)
			GMessage.message_error(editorPatologie.getString("SELEZIONARE LA PATOLOGIA DA MODIFICARE E POI PREMERE IL PULSANTE MODIFICA PATOLOGIA"));
		else
		{

			//Setta la variabile modalita
                        modalita=Modalita.modifica;
                        txModalita.setText(modModifica);
                        txPatologiaSelezionata.setText(String.valueOf(
                                new Integer(tabellaPatologie.getSelectedRow())));
			//Recupero valori ID NOME COGNOME
			Object id = tabellaPatologie.getValueAt(tabellaPatologie.getSelectedRow(), tabellaPatologie.getColumnModel().getColumnIndex(PatologiaMySqlDAO.NOME_COLONNA_CODICE));
			Object nome= tabellaPatologie.getValueAt(tabellaPatologie.getSelectedRow(), tabellaPatologie.getColumnModel().getColumnIndex(PatologiaMySqlDAO.NOME_COLONNA_NOME));

			//Setta il modulo per l'inserimento
			txID.setText(String.valueOf(id));
			txNome.setText(String.valueOf(nome));
			txInfo.setText(editorPatologie.getString("MODIFICA PATOLOGIA MODIFICARE CODICE, NOME E PREMERE OK."));
		}   }

    /**
     * @param args the command line arguments
     */
    	public static void start() {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if (editorPatologie.getString("NIMBUS").equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditorPatologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditorPatologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditorPatologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditorPatologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
                            try {
                                EditorPatologie window = new EditorPatologie(new javax.swing.JFrame(), true);
                                Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit().getScreenSize();
                                window.setLocation(new Point( (risoluzioneSchermo.width - window.getWidth()) /2, (risoluzioneSchermo.height - window.getHeight()) /2)  );
                                window.setVisible(true);
                            } catch (MainException ex) {
                                Logger.getLogger(EditorPatologie.class.getName()).log(Level.SEVERE, null, ex);
                            }
			}
		});
	}
    // Variables declaration - do not modify                     
    private javax.swing.JLabel immagineTestataPatologie;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pannelloModifica;
    private javax.swing.JButton pulsanteAggiungi;
    private javax.swing.JButton pulsanteCancella;
    private javax.swing.JButton pulsanteCancellaTutti;
    private javax.swing.JButton pulsanteEsci;
    private javax.swing.JButton pulsanteHome;
    private javax.swing.JButton pulsanteModifica;
    private javax.swing.JButton pulsanteOK;
    private javax.swing.JTable tabellaPatologie;
    private javax.swing.JFormattedTextField txID;
    private javax.swing.JTextArea txInfo;
    private javax.swing.JTextField txModalita;
    private javax.swing.JTextField txNome;
    private javax.swing.JFormattedTextField txPatologiaSelezionata;
    // End of variables declaration                   

    
    /*private void codFormat() {
        txID.setDocument(new CodiceFormat());
    }*/

    private final String modAggiungi = editorPatologie.getString("AGGIUNGI");
    private final String modModifica = editorPatologie.getString("MODIFICA N.");

    @Override
    public void apri() {
        start();
    }
     
    private enum Modalita{aggiungi, modifica}
    private Modalita modalita;
    private int rigaSelezionata = -1;
}
