/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adisys.server.boundary;

import messaggistica.GMessage;
import messaggistica.MainException;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import presentation.FrontController;
import presentation.RequestManager;

/**
*
* @author Gianmarco Divittorio
* @author Nicola Gazzilli
*/
public class EditorScelta extends javax.swing.JFrame implements Boundary {
    private static ResourceBundle editorScelta = ResourceBundle.getBundle("adisys/server/property/EditorScelta");
    private FrontController FC;
    
    public static void setResourceBundle(String path, Locale locale){
        editorScelta = ResourceBundle.getBundle(path, locale);
    }
 
	/**
	 * Creates new form ADISysGUI
	 */
	public EditorScelta() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        intestazione = new javax.swing.JLabel();
        pulsanteEsci = new javax.swing.JButton();
        pulsanteIndietro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txInfoData2 = new javax.swing.JTextArea();
        txAdisysDatabase = new javax.swing.JButton();
        txAdisysServer2 = new javax.swing.JButton();
        barraDeiMenu = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(editorScelta.getString("ADISYS - SCELTA SERVIZIO")); // NOI18N
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(700, 425));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        intestazione.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/decorazioniFinestre/EditorScelta.png"))); // NOI18N

        pulsanteEsci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/arresta.png"))); // NOI18N
        pulsanteEsci.setText(editorScelta.getString("ABBANDONA ADISYS")); // NOI18N
        pulsanteEsci.setToolTipText(editorScelta.getString("ESCI DA ADISYS")); // NOI18N
        pulsanteEsci.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEsciActionPerformed(evt);
            }
        });

        pulsanteIndietro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/indietro.png"))); // NOI18N
        pulsanteIndietro.setText(editorScelta.getString("TORNA A SELEZIONE LINGUA")); // NOI18N
        pulsanteIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteIndietroActionPerformed(evt);
            }
        });

        txInfoData2.setEditable(false);
        txInfoData2.setBackground(new java.awt.Color(240, 240, 240));
        txInfoData2.setLineWrap(true);
        txInfoData2.setText(editorScelta.getString("Seleziona il servizio che preferisci. Con ADISysServer2 sarà possibile accedere ad un portale per un'accurata gestione del servizio di assistenza  domiciliare. ADISysDatabase ha uno scopo meramente dimostrativo del comportamento del sistema al variare della  struttura del DBMS per quanto riguarda la denominazione di campi e tabelle.")); // NOI18N
        jScrollPane1.setViewportView(txInfoData2);

        txAdisysDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/database_edit.png"))); // NOI18N
        txAdisysDatabase.setText(editorScelta.getString("ADISYSDATABASE")); // NOI18N
        txAdisysDatabase.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txAdisysDatabase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txAdisysDatabase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txAdisysDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAdisysDatabaseActionPerformed(evt);
            }
        });

        txAdisysServer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/LOGOFARMACIA_300_Logo Farmacia piccolo Verde.png"))); // NOI18N
        txAdisysServer2.setText("ADISysServer3");
        txAdisysServer2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txAdisysServer2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txAdisysServer2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txAdisysServer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAdisysServer2ActionPerformed(evt);
            }
        });

        barraDeiMenu.setRequestFocusEnabled(false);
        setJMenuBar(barraDeiMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intestazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pulsanteEsci)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pulsanteIndietro))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txAdisysServer2)
                .addGap(80, 80, 80)
                .addComponent(txAdisysDatabase)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(intestazione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txAdisysServer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txAdisysDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pulsanteEsci, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pulsanteIndietro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        
      
    private void pulsanteEsciActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(GMessage.confirm(editorScelta.getString("SEI SICURO DI VOLER ABBANDONARE")
            + editorScelta.getString(" ADISYS?")) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }                                            

    private void pulsanteIndietroActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.dispose();
        try {
            request(RequestManager.APRI_EDITOR_LANGUAGE);
        } catch (MainException ex) {
            Logger.getLogger(EditorScelta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                

    private void txAdisysDatabaseActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.dispose();
        try {
            request(RequestManager.APRI_EDITOR_DATABASE);
        } catch (MainException ex) {
            Logger.getLogger(EditorScelta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                

    private void txAdisysServer2ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.dispose();
        try {
            request(RequestManager.APRI_PIANIFICATORE);
        } catch (MainException ex) {
            Logger.getLogger(EditorScelta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                               

    private void request(String request) throws MainException{
        FC = RequestManager.getFCInstance();
        RequestManager.getFCInstance().addService();
        if(FC.processRequest(request)){
            System.out.println("Finestra " + request + " aperta con successo.");
        }
        else{
            messaggistica.GMessage.winNotFound(request);
        }
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        if(GMessage.confirm(editorScelta.getString("SEI SICURO DI VOLER USCIRE DA")
                 + editorScelta.getString(" ADISYS?"))   
                 == JOptionPane.YES_OPTION) {
             System.exit(0);
         }
    }                                  

	/**
	 *
	 */
	public static void start() {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if (editorScelta.getString("NIMBUS").equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditorScelta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditorScelta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditorScelta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditorScelta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				EditorScelta window = new EditorScelta();
				Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit().getScreenSize();
				window.setLocation(new Point( (risoluzioneSchermo.width - window.getWidth()) /2, (risoluzioneSchermo.height - window.getHeight()) /2)  );
				window.setVisible(true);

			}
		});

	}
        

    // Variables declaration - do not modify                     
    private javax.swing.JMenuBar barraDeiMenu;
    private javax.swing.JLabel intestazione;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pulsanteEsci;
    private javax.swing.JButton pulsanteIndietro;
    private javax.swing.JButton txAdisysDatabase;
    private javax.swing.JButton txAdisysServer2;
    private javax.swing.JTextArea txInfoData2;
    // End of variables declaration                   

    @Override
    public void open() {
        start();
    }

}
