/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adisys.server.boundary;

import adisys.server.strumenti.DateFormatConverter;
import adisys.server.strumenti.VariableTableModel;
import business.paziente.PazienteTO;
import messaggistica.MainException;
import integration.dao.PazienteMySqlDAO;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import presentation.FrontController;
import presentation.RequestManager;
import adisys.server.strumenti.Record;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import messaggistica.GMessage;

    // Variables declaration - do not modify                     
/**
*
* @author Gianmarco Divittorio
* @author Nicola Gazzilli
*/
public class EditorPazienti extends javax.swing.JDialog implements Boundary {
    
    private static ResourceBundle editorPazienti = ResourceBundle.getBundle("adisys/server/property/EditorPazienti");
    private static EditorPazienti window;
    private static final String FORMATO_DATA_NASCITA  = DateFormatConverter.getFormatData();
    private static final String FORMATO_DATA_TABELLA = "yyyy-MM-dd";
    private static EditorInterventi tmp = null;
    private static final int LUNGHEZZAMASSIMANOME = 20;
    private static final int LUNGHEZZAMASSIMACOGNOME = 20;
    private static final int LUNGHEZZA_MASSIMA_CELLULARE = 10;
    private FrontController FC;

        public static void setEditorInterventi(EditorInterventi editor){
            tmp = editor;
        } 

         public static void setResourceBundle(String path, Locale locale){
             editorPazienti = ResourceBundle.getBundle(path, locale);
         }
    
	/**
	 * Creates new form dialogoPazienti
	 */
	public EditorPazienti(java.awt.Frame parent, boolean modal) throws MainException {
		super(parent, modal);
		initComponents();
		modelloListaCellulari = new DefaultListModel<>();
		aggiornaTabella();
		impostaModuloNuovoPaziente();
	}
        
        public EditorPazienti(){
            
        }
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        immagineTestataPazienti = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabellaPazienti = new javax.swing.JTable();
        jPanel23 = new javax.swing.JPanel();
        txErrore = new javax.swing.JLabel();
        labelCellulare = new javax.swing.JLabel();
        txCellularePaziente = new javax.swing.JFormattedTextField();
        labelCognome = new javax.swing.JLabel();
        txCognomePaziente = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        txNomePaziente = new javax.swing.JTextField();
        pulsanteOK = new javax.swing.JButton();
        labelDataNascita = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCellulari = new javax.swing.JList();
        pRemCellulare = new javax.swing.JButton();
        pAddCellulare = new javax.swing.JButton();
        pulsanteHome = new javax.swing.JButton();
        dataCalendar = new com.toedter.calendar.JDateChooser();
        pulsanteEsci = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        pulsanteAggiungi = new javax.swing.JButton();
        pulsanteModifica = new javax.swing.JButton();
        pulsanteCancella = new javax.swing.JButton();
        pulsanteCancellaTutti = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txModalita = new javax.swing.JTextField();
        txPazienteSelezionato = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(editorPazienti.getString("TITLE")); // NOI18N
        setMinimumSize(new java.awt.Dimension(640, 480));
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        immagineTestataPazienti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/decorazioniFinestre/Pazienti.png"))); // NOI18N

        tabellaPazienti.setToolTipText(editorPazienti.getString("PREMERE P PER INFO SUL PAZIENTE")); // NOI18N
        tabellaPazienti.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaPazienti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabellaPazientiKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tabellaPazienti);

        txErrore.setForeground(new java.awt.Color(255, 0, 0));
        txErrore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txErrore.setText(editorPazienti.getString("MESSAGGIO")); // NOI18N

        labelCellulare.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCellulare.setText(editorPazienti.getString("CELLULARE")); // NOI18N
        labelCellulare.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelCognome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCognome.setText(editorPazienti.getString("COGNOME PAZIENTE")); // NOI18N
        labelCognome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNome.setText(editorPazienti.getString("NOME PAZIENTE")); // NOI18N
        labelNome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        pulsanteOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/iconainserisci.png"))); // NOI18N
        pulsanteOK.setText(editorPazienti.getString("OK")); // NOI18N
        pulsanteOK.setToolTipText(editorPazienti.getString("EFFETTUA OPERAZIONE")); // NOI18N
        pulsanteOK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteOKActionPerformed(evt);
            }
        });

        labelDataNascita.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDataNascita.setText(editorPazienti.getString("DATA DI NASCITA (GG/MM/AAAA)")); // NOI18N
        labelDataNascita.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        listaCellulari.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaCellulari);

        pRemCellulare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/rem/normale.png"))); // NOI18N
        pRemCellulare.setBorder(null);
        pRemCellulare.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/rem/down.png"))); // NOI18N
        pRemCellulare.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/rem/over.png"))); // NOI18N
        pRemCellulare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pRemCellulareActionPerformed(evt);
            }
        });

        pAddCellulare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/add/normale.png"))); // NOI18N
        pAddCellulare.setBorder(null);
        pAddCellulare.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/add/down.png"))); // NOI18N
        pAddCellulare.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/add/over.png"))); // NOI18N
        pAddCellulare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAddCellulareActionPerformed(evt);
            }
        });

        pulsanteHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/home.png"))); // NOI18N
        pulsanteHome.setText(editorPazienti.getString("HOME")); // NOI18N
        pulsanteHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteHomeActionPerformed(evt);
            }
        });

        dataCalendar.setDateFormatString(editorPazienti.getString("DD/MM/YYYY")); // NOI18N
        dataCalendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataCalendarPropertyChange(evt);
            }
        });

        pulsanteEsci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/arresta.png"))); // NOI18N
        pulsanteEsci.setText(editorPazienti.getString("ABBANDONA ADISYS")); // NOI18N
        pulsanteEsci.setToolTipText(editorPazienti.getString("ESCI DA ADISYS")); // NOI18N
        pulsanteEsci.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEsciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(labelCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txNomePaziente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txCognomePaziente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDataNascita)
                            .addComponent(dataCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pulsanteEsci)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(txCellularePaziente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(pAddCellulare))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(pRemCellulare)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pulsanteOK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulsanteHome, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txErrore, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCellulare))
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCognomePaziente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNomePaziente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDataNascita, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(dataCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pulsanteEsci))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txErrore)
                        .addGap(18, 18, 18)
                        .addComponent(labelCellulare, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txCellularePaziente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pAddCellulare))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pRemCellulare)))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(pulsanteOK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pulsanteHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jToolBar1.setFloatable(false);

        pulsanteAggiungi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaAggiungi.png"))); // NOI18N
        pulsanteAggiungi.setText(editorPazienti.getString("AGGIUNGI PAZIENTE")); // NOI18N
        pulsanteAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteAggiungiActionPerformed(evt);
            }
        });
        jToolBar1.add(pulsanteAggiungi);

        pulsanteModifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaModifica.png"))); // NOI18N
        pulsanteModifica.setText(editorPazienti.getString("MODIFICA PAZIENTE")); // NOI18N
        pulsanteModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteModificaActionPerformed(evt);
            }
        });
        jToolBar1.add(pulsanteModifica);

        pulsanteCancella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaCancella.png"))); // NOI18N
        pulsanteCancella.setText(editorPazienti.getString("CANCELLA PAZIENTE")); // NOI18N
        pulsanteCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteCancellaActionPerformed(evt);
            }
        });
        jToolBar1.add(pulsanteCancella);

        pulsanteCancellaTutti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaCancellaTutti.png"))); // NOI18N
        pulsanteCancellaTutti.setText(editorPazienti.getString("CANCELLA TUTTI I PAZIENTI")); // NOI18N
        pulsanteCancellaTutti.setFocusable(false);
        pulsanteCancellaTutti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteCancellaTuttiActionPerformed(evt);
            }
        });
        jToolBar1.add(pulsanteCancellaTutti);

        jLabel1.setText(editorPazienti.getString("UNA VOLTA SELEZIONATO UN PAZIENTE PREMERE 'P' PER VISUALIZZARNE LE INFORMAZIONI.")); // NOI18N

        txModalita.setEditable(false);
        txModalita.setText(editorPazienti.getString("OPERAZIONE")); // NOI18N

        txPazienteSelezionato.setEditable(false);
        txPazienteSelezionato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(immagineTestataPazienti)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txModalita, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPazienteSelezionato, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(immagineTestataPazienti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txModalita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(txPazienteSelezionato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
	

	private void pulsanteOKActionPerformed(java.awt.event.ActionEvent evt) {                                           
  
            FC = RequestManager.getFCInstance();
            rigaSelezionata = -1;
            if (modalita==Modalita.aggiungi) {
                if(datiValidi()){
                    if(GMessage.confirm(editorPazienti.getString("CREARE NUOVO PAZIENTE")) == 
                       JOptionPane.YES_OPTION){
                            PazienteTO to;
                            try {
                                to = getValueJustInsert();
                                 ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
                                 params.add(new Record<String, Object>("business.paziente.PazienteTO", to));
                            try {
                                boolean ok = (boolean) FC.processRequest("creaPaziente", params);
                                if(ok){
                                //Aggiunta al database
                                    String messaggio = java.text.MessageFormat.format(editorPazienti.getString("PAZIENTE: {0} "), 
                                            new Object[] {to.getNome().toUpperCase()}) + " " + 
                                            to.getCognome().toUpperCase() + editorPazienti.getString("CREATO CON SUCCESSO!");
                                     if(tmp != null)
                                        tmp.aggiornaPazienti();
                                     GMessage.information(messaggio);
                                    impostaModuloNuovoPaziente();
                                } else {
                                    //Caso paziente non aggiunto
                                    String messaggio= editorPazienti.getString("SI È VERIFICATO UN ERRORE, IMPOSSIBILE CREARE IL PAZIENTE");
				GMessage.message_error(messaggio);
                                }
                            } catch (MainException ex) {
                                Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } catch (ParseException ex) {
                            Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            } else if (modalita==Modalita.modifica){
                    rigaSelezionata = tabellaPazienti.getSelectedRow();
                    //Caso ID noto modifica i dati

                    if(datiValidi()){
                     if(GMessage.confirm(editorPazienti.getString("SEI SICURO DI MODIFICARE")) == 
                       JOptionPane.YES_OPTION){
                         PazienteTO to;
                        try {
                        to = getValueJustUpdate();
                        ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
                        params.add(new Record<String, Object>("business.paziente.PazienteTO", to));
                        try {
                            boolean ok = (boolean) FC.processRequest("modificaPaziente", params);
                            if(ok){
                            //Aggiunta al database
                                String messaggio = java.text.MessageFormat.format(editorPazienti.getString("PAZIENTE: {0} "), new Object[] {
                                    tabellaPazienti.getValueAt(rigaSelezionata,
                                    tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_NOME)).
                                    toString().toUpperCase()}) 
                                    + " " + tabellaPazienti.getValueAt(rigaSelezionata,
                                    tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_COGNOME)).
                                    toString().toUpperCase() + "\n" + 
                                    DateFormatConverter.cambiaFormato(tabellaPazienti.getValueAt(rigaSelezionata,
                                    tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_DATA_NASCITA)).toString(),
                                    FORMATO_DATA_TABELLA, FORMATO_DATA_NASCITA);
                                 
                                    messaggio = messaggio + editorPazienti.getString("MODIFICATO IN:") +
                                    to.getNome().toUpperCase() + " " + to.getCognome().toUpperCase() +
                                            "\n" + to.getDataNascita(FORMATO_DATA_NASCITA);
                               
                                    messaggio += editorPazienti.getString("CON SUCCESSO!");
                                    if(tmp != null)
                                        tmp.aggiornaPazienti();
                                    GMessage.information(messaggio);
                                    impostaModuloNuovoPaziente();
                            }
                            else
                            {
				//Caso paziente non aggiunto
				String messaggio= editorPazienti.getString("SI È VERIFICATO UN ERRORE, IMPOSSIBILE MODIFICARE IL PAZIENTE");
				GMessage.message_error(messaggio);
                            }
                        
                        } catch (MainException ex) {
                            Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (ParseException ex) {
                        Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
                    }
						
                }//IF SU DATI VALILDI
            }
        }
        try {
            //Aggiornamento tabella
            aggiornaTabella();
        } catch (MainException ex) {
            Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
        }
	}                                          

        /**
	 * Restituisce i valori dei campi appena inseriti
	 * @return una struttura dati di String con i valori appena inseriti
	 * @throws ParseException 
	*/
	private PazienteTO getValueJustInsert() throws ParseException{
		
                    PazienteTO to = new PazienteTO(txNomePaziente.getText().toUpperCase(), 
                            txCognomePaziente.getText().toUpperCase(),
                        txDataNascita, modelloListaCellulari.toArray());
		System.out.println(to);
		
		return to;
		
	}
        
        /**
	 * Restituisce i valori dei campi appena inseriti
	 * @return una struttura dati di String con i valori appena inseriti
	 * @throws ParseException 
	*/
	private PazienteTO getValueJustUpdate() throws ParseException{
		
		PazienteTO to = new PazienteTO(
                        Integer.parseInt(txPazienteSelezionato.getText()), txNomePaziente.getText(), 
                        txCognomePaziente.getText(), txDataNascita, modelloListaCellulari.toArray());
		System.out.println(to);
		
		return to;
		
	}
        
	private void pulsanteModificaActionPerformed(java.awt.event.ActionEvent evt) {                                                 

		impostaModuloModificaPaziente();

	}                                                

	private void pulsanteAggiungiActionPerformed(java.awt.event.ActionEvent evt) {                                                 

		impostaModuloNuovoPaziente();

	}                                                

	private void pulsanteCancellaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if(tabellaPazienti.getSelectedRow()==-1)
            GMessage.information(editorPazienti.getString("SELEZIONARE IL PAZIENTE DA CANCELLARE E POI PREMERE IL PULSANTE CANCELLA PAZIENTE"));
        else {
            String nome = tabellaPazienti.getValueAt(tabellaPazienti.getSelectedRow(),
                    tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_NOME)).toString();
            String cognome = tabellaPazienti.getValueAt(tabellaPazienti.getSelectedRow(),
                    tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_COGNOME)).toString();
            String nominativo = nome + " " + cognome;
            String messaggio = editorPazienti.getString("CANCELLARE IL PAZIENTE") + " " + nominativo + "?";
	    messaggio += editorPazienti.getString("SARANNO PERSI ANCHE TUTTI I DATI RELATIVI AGLI INTERVENTI");
	    messaggio += editorPazienti.getString("SE CI SONO INTERVENTI ASSEGNATI AL PAZIENTE E' OPPORTUNO MODIFICARE L'ASSEGNAZIONE.");

            //VISUALIZZAZIONE MESSAGGIO
            if(GMessage.confirm(messaggio) == JOptionPane.YES_OPTION){
                   //Recupero ID
            Object id = tabellaPazienti.getValueAt(tabellaPazienti.getSelectedRow(), 
                    tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_ID));
            String dataNascita = tabellaPazienti.getValueAt(tabellaPazienti.getSelectedRow(), 
                    tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_DATA_NASCITA)).toString();
            //Casting ID
            int idInt=Integer.valueOf(String.valueOf(id));
            dataNascita = DateFormatConverter.cambiaFormato(dataNascita, FORMATO_DATA_TABELLA, 
                    FORMATO_DATA_NASCITA);
            PazienteTO to = new PazienteTO(idInt, nome, cognome, dataNascita, modelloListaCellulari.toArray());
            System.out.println("Evento pulsante CancellaPaziente : "+ to);
            ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
            params.add(new Record<String, Object>("business.paziente.PazienteTO", to));
            try {
                if((Boolean) FC.processRequest("cancellaPaziente", params)){
                    System.out.println("Cancellazione del paziente eseguita con successo");
                    messaggio = java.text.MessageFormat.format(editorPazienti.getString("PAZIENTE: {0} "), 
                            new Object[] {to.getNome().toUpperCase()}) + " " + to.getCognome().toUpperCase() + 
                            "\n" + to.getDataNascita(FORMATO_DATA_NASCITA) +
                            editorPazienti.getString("CANCELLATO CON SUCCESSO!");
                    GMessage.information(messaggio);
                }
                else{
                    GMessage.message_error(editorPazienti.getString("CANCPAZIENTE"));
                }
            } catch (MainException ex) {
                Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
            }
			
            try {
                //Aggiornamento tabella
                aggiornaTabella();
                if(tmp != null)
                    tmp.aggiornaPazienti();
            } catch (MainException ex) {
                Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            }
        }
	}                                                

	private void pulsanteCancellaTuttiActionPerformed(java.awt.event.ActionEvent evt) {                                                      
            String messaggio = editorPazienti.getString("CONFERMARE LA CANCELLAZIONE DI TUTTI I PAZIENTI?L'OPERAZIONE NON POTRA' ESSERE ANNULLATA E SARANNO CANCELLATI TUTTI GLI INTERVENTI DAL DATABASE");
            //VISUALIZZAZIONE MESSAGGIO
            if(GMessage.confirm(messaggio) == JOptionPane.YES_OPTION){
                System.out.println("Evento pulsante CancellaTuttiPazienti");
                try {
                    if((Boolean) FC.processRequest("cancellaTuttiPazienti", null)) {
                        System.out.println("Cancellazione di tutti i pazienti avvenuta con successo");
                        messaggio = editorPazienti.getString("TUTTI I PAZIENTI SONO STATI CANCELLATI CON SUCCESSO!");
                        if(tmp != null)
                            tmp.aggiornaPazienti();
                        GMessage.information(messaggio);
                    } else {
                        GMessage.message_error(editorPazienti.getString("CANCTUTTI"));
                    }
                } catch (MainException ex) {
                    Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
	}                                                     

	private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
            try {
                aggiornaTabella();
            } catch (MainException ex) {
                Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
            }
	}                                    

	private void pAddCellulareActionPerformed(java.awt.event.ActionEvent evt) {                                              
		if(!txCellularePaziente.getText().isEmpty())
                {
                //Aggiunge il nuovo numero alla lista
		modelloListaCellulari.addElement(txCellularePaziente.getText());
               
                //Aggiorna la view
                listaCellulari.setModel(modelloListaCellulari);
                
                //Svuota il campo di inserimento
                txCellularePaziente.setText("");
                }
                /*else
                    GMessage.message_error(editorPazienti.getString("NUMERO DI CELLULARE NON SPECIFICATO."));*/
                
	}                                             

	private void pRemCellulareActionPerformed(java.awt.event.ActionEvent evt) {                                              
                //Ricava l'indice dell'elemento selezionato
		int indice = listaCellulari.getSelectedIndex();
                
                //Se l'indice è valido (c'è un elem selezionato) rimuove l'elemento
                if (indice!= -1) modelloListaCellulari.remove(indice);
                
                //Aggiorna la view
                listaCellulari.setModel(modelloListaCellulari);
	}                                             

        public boolean datiValidi()
	{
		String messaggio =editorPazienti.getString("ATTENZIONE");
		int errori=0;
		if (txNomePaziente.getText().isEmpty())
		{
			errori++;
			messaggio += editorPazienti.getString("NOME PAZIENTE VUOTO");
		} else if(txNomePaziente.getText().length() > LUNGHEZZAMASSIMANOME){
                        errori++;
			messaggio += editorPazienti.getString("NOME PAZIENTE TROPPO LUNGO (MAX");
                        messaggio += LUNGHEZZAMASSIMANOME + " ";
                        messaggio += editorPazienti.getString("CAR)");
                }
                boolean numeric = false;
                for(int i = 0; i < txNomePaziente.getText().length(); i++){
                    if(txNomePaziente.getText().toCharArray()[i] >= '0' 
                            && txNomePaziente.getText().toCharArray()[i] <= '9'){
                        numeric = true;
                        break;
                    }
                }
                if(numeric == true){
                        errori++;
			messaggio += editorPazienti.getString("IL NOME DEL PAZIENTE CONTIENE CARATTERI NUMERICI");
                }
		if(txCognomePaziente.getText().isEmpty())
		{
			errori++;
                        messaggio += editorPazienti.getString("COGNOME PAZIENTE VUOTO");
		} else if(txCognomePaziente.getText().length() > LUNGHEZZAMASSIMACOGNOME){
                        errori++;
                        messaggio += editorPazienti.getString("COGNOME PAZIENTE TROPPO LUNGO (MAX");
                        messaggio += LUNGHEZZAMASSIMACOGNOME + " ";
                        messaggio += editorPazienti.getString("CAR)");
                }
                numeric = false;
                for(int i = 0; i < txCognomePaziente.getText().length(); i++){
                    if(txCognomePaziente.getText().toCharArray()[i] >= '0' 
                            && txCognomePaziente.getText().toCharArray()[i] <= '9'){
                        numeric = true;
                        break;
                    }
                }
                if(numeric == true){
                        errori++;
			messaggio += editorPazienti.getString("IL COGNOME DEL PAZIENTE CONTIENE CARATTERI NUMERICI");
                }
                if (txDataNascita.isEmpty()){
                    errori++;
                    messaggio += editorPazienti.getString("DATA DI NASCITA NON SPECIFICATA");
                } else if(!DateFormatConverter.parseable(txDataNascita, FORMATO_DATA_NASCITA)) {
                    errori++;
                    messaggio += editorPazienti.getString("FORMATO DATA DI NASCITA NON VALIDO");
                    messaggio += " (" + FORMATO_DATA_NASCITA + ")";
                }
                Object[] cellulari = modelloListaCellulari.toArray();
                for(int i = 0; i < cellulari.length; i++){
                    if (cellulari[i].toString().isEmpty()){
                        errori++;
                        messaggio += editorPazienti.getString("NUMERO DI CELLULARE") + " no. " + (i + 1)
                                + " " + editorPazienti.getString("VUOTO");
                    }
                    else if(cellulari[i].toString().length() > LUNGHEZZA_MASSIMA_CELLULARE){
                        errori++;
                        messaggio += editorPazienti.getString("NUMERO DI CELLULARE") + " no. " + (i + 1)
                                + " " + editorPazienti.getString("TROPPO LUNGO (MAX") + 
                                LUNGHEZZA_MASSIMA_CELLULARE + " " + editorPazienti.getString("CAR)");
                    }
                    else {
                        boolean validate = validateTelFaxNumber(cellulari[i].toString());
                        if(validate == false){
                            errori++;
                            messaggio += editorPazienti.getString("NUMERO DI CELLULARE") + " no. " + (i + 1)
                                    + " " + editorPazienti.getString("SOLO CARATTERI NUMERICI");
                        }
                    }
                    
                }    
		if (errori==0) return true;
		else 
		{
			messaggio+= "\n"+String.valueOf(errori)+editorPazienti.getString(" ERRORI RILEVATI.");
			GMessage.message_error(messaggio);
			return false;
		}

	}
        
        public boolean validateTelFaxNumber(String number) {            
            if (number == null) {
                return false;
            }
            
            if(number.contains("/") || number.contains("\\") || number.contains("-") 
                    || number.contains("+"))
                return false;
            
            String patternSpace = "\\s+";
            String replaceStr = "";
            Pattern pattern = Pattern.compile(patternSpace);
            Matcher matcher = pattern.matcher(number);
            number = matcher.replaceAll(replaceStr);

            patternSpace = "\\-+";
            replaceStr = "";
            pattern = Pattern.compile(patternSpace);
            matcher = pattern.matcher(number);
            number = matcher.replaceAll(replaceStr);    

            //i caratteri / non vengono presi in considerazione
            patternSpace = "\\/+";
            replaceStr = "";
            pattern = Pattern.compile(patternSpace);
            matcher = pattern.matcher(number);
            number = matcher.replaceAll(replaceStr);

            Pattern p = Pattern.compile("^(\\+)?[0-9]+$");
            Matcher m = p.matcher(number);
            boolean matchFound = m.matches();
            return matchFound;
}
        
        
    private void tabellaPazientiKeyPressed(java.awt.event.KeyEvent evt) {                                           
                if((evt.getKeyChar()== 'p' || evt.getKeyChar()== 'P')
                        && tabellaPazienti.getColumnCount() != 1)
                {
                	//Recupero valore ID
                	int colonnaID = tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_ID);
        			int selectedID = Integer.valueOf(String.valueOf(tabellaPazienti.getValueAt(tabellaPazienti.getSelectedRow(), colonnaID)));
                
                	//Recupero informazioni
                    if (selectedID !=-1) {
                        //TODO Caricamento numeri di cellulare
                        PazienteTO to = new PazienteTO();
                        to.setID(selectedID);
                        ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
                        params.add(new Record<String, Object>("business.paziente.PazienteTO", to));
                        //Caso no ID -> NUOVO PAZIENTE: effettua l'inserimento
                       
                        try {
                            GMessage.information((String) FC.processRequest(
                                    "visualizzaPaziente", params));

                        } catch (MainException ex) {
                                Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
        }   
    }                                          

    private void pulsanteHomeActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(GMessage.confirm(editorPazienti.getString("SEI SICURO DI VOLER USCIRE DALL'")
                 + editorPazienti.getString("EDITOR DEI PAZIENTI E TORNARE ALLA HOME?"))   
                 == JOptionPane.YES_OPTION) {
             this.dispose();
        }
    }                                            

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
         if(GMessage.confirm(editorPazienti.getString("SEI SICURO DI VOLER USCIRE DALL'")
                 + editorPazienti.getString("EDITOR DEI PAZIENTI"))   
                 == JOptionPane.YES_OPTION) {
             this.dispose();
        }
    }                                  

    private void dataCalendarPropertyChange(java.beans.PropertyChangeEvent evt) {                                            
        if(dataCalendar.getDate() != null){
                    SimpleDateFormat dateFormat = new SimpleDateFormat(FORMATO_DATA_NASCITA);
                    txDataNascita = dateFormat.format(dataCalendar.getDate());
                }
    }                                           

    private void pulsanteEsciActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(GMessage.confirm(editorPazienti.getString("SEI SICURO DI VOLER ABBANDONARE")
            + editorPazienti.getString(" ADISYS?")) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }                                            

	public void aggiornaTabella() throws MainException{
                
		//apre il front controller per farsi dare i dati da inserire nella tabella
		FC = RequestManager.getFCInstance();
		AbstractTableModel modelAdisys = (AbstractTableModel) FC.processRequest("visualizzaPazienti", null);
		tabellaPazienti.setModel(modelAdisys);
                
                if(tabellaPazienti.getRowCount() == 0){
                    VariableTableModel modello = new VariableTableModel();
                    modello.addColumn("");
                     String[] msg = {editorPazienti.getString("NON È STATO TROVATO ALCUN PAZIENTE REGISTRATO NEL")
                        + editorPazienti.getString(" SISTEMA.")};
                     modello.addRow(msg);
                     tabellaPazienti.setModel(modello);
                     pulsanteModifica.setVisible(false);
                     pulsanteCancella.setVisible(false);
                     pulsanteCancellaTutti.setVisible(false);
                     jLabel1.setVisible(false);
                     return;
                }
                 if(pulsanteModifica.isVisible() == false){
                     pulsanteModifica.setVisible(true);
                     pulsanteCancella.setVisible(true);
                     pulsanteCancellaTutti.setVisible(true);
                     jLabel1.setVisible(true);
                 }
                if(rigaSelezionata != -1)
                    tabellaPazienti.setRowSelectionInterval(rigaSelezionata, rigaSelezionata);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void start() {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if (editorPazienti.getString("NIMBUS").equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditorPazienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditorPazienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditorPazienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditorPazienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
                            try {
                                window = new EditorPazienti(new javax.swing.JFrame(), true);
                            } catch (MainException ex) {
                                Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
                            }
				Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit().getScreenSize();
				window.setLocation(new Point( (risoluzioneSchermo.width - window.getWidth()) /2, (risoluzioneSchermo.height - window.getHeight()) /2)  );
				window.setVisible(true);
			}
		});
	}

	public void impostaModuloNuovoPaziente()
	{
            	//Setta la variabile modalita
		modalita=Modalita.aggiungi;
                txModalita.setText(modAggiungi);
                txPazienteSelezionato.setText("");
		//Inserimento nel modulo
		txNomePaziente.setText("");
		txCognomePaziente.setText("");
		dataCalendar.setDate(null);
		txCellularePaziente.setText("");
                modelloListaCellulari.clear();
                listaCellulari.setModel(modelloListaCellulari);

		//Commento
		txErrore.setText(editorPazienti.getString("AGGIUNGI PAZIENTE: INSERIRE I DATI E PREMERE OK"));
	}

	public void impostaModuloModificaPaziente()
	{
		if (tabellaPazienti.getSelectedRow()==-1)
		{
			//Non si cono pazienti selezionati. Nessuna modifica possibile
			GMessage.message_error(editorPazienti.getString("IMPOSSIBILE MODIFICARE: NESSUN PAZIENTE SELEZIONATO."));
		}
		else
		{
			//Identificazione delle colonna 
                        modalita=Modalita.modifica;
                        txModalita.setText(modModifica);
			int colonnaID = tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_ID);
			int colonnaNome = tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_NOME);
			int colonnaCognome = tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_COGNOME);
			int colonnaDataNascita = tabellaPazienti.getColumnModel().getColumnIndex(PazienteMySqlDAO.NOME_COLONNA_DATA_NASCITA);
			
			//Nel caso non sia identificata la colonna ID
			if (colonnaID<0)
			{
				GMessage.message_error(editorPazienti.getString("COLONNA ") + 
                                        PazienteMySqlDAO.NOME_COLONNA_ID + editorPazienti.getString(" NON TROVATA."));
				return;
			}


			//Lettura dei valori
			Object selectedID = tabellaPazienti.getValueAt(tabellaPazienti.getSelectedRow(), colonnaID);
			Object selectedNome = tabellaPazienti.getValueAt(tabellaPazienti.getSelectedRow(), colonnaNome);
			Object selectedCognome = tabellaPazienti.getValueAt(tabellaPazienti.getSelectedRow(), colonnaCognome);
			Object selectedDataNascita = tabellaPazienti.getValueAt(tabellaPazienti.getSelectedRow(), colonnaDataNascita);
			
			//Inserimento nel modulo
			txPazienteSelezionato.setText(String.valueOf(selectedID));
			txNomePaziente.setText(String.valueOf(selectedNome));
			txCognomePaziente.setText(String.valueOf(selectedCognome));
                        long dateLong = DateFormatConverter.dateString2long(selectedDataNascita.toString(), 
                               FORMATO_DATA_TABELLA);
                        dataCalendar.setDate(new Date(dateLong));
			
                        //TODO Caricamento numeri di cellulare
                        PazienteTO to = new PazienteTO();
                        to.setID(Integer.parseInt(selectedID.toString()));
                        ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
                        params.add(new Record<String, Object>("business.paziente.PazienteTO", to));
                        //Caso no ID -> NUOVO PAZIENTE: effettua l'inserimento
                       
                        try {
                            modelloListaCellulari = (DefaultListModel<String>) FC.processRequest(
                                    "visualizzaNumeriTelefono", params);
                            listaCellulari.setModel(modelloListaCellulari);
                        } catch (MainException ex) {
                                Logger.getLogger(EditorPazienti.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
			//Commento
			txErrore.setText(java.text.MessageFormat.format(editorPazienti.getString("MODIFICA PAZIENTE{0}{1}"),
                                new Object[] {
                                    String.valueOf(selectedNome), 
                                    String.valueOf(selectedCognome)
                                }));
		}

        }

    // Variables declaration - do not modify                     
    private com.toedter.calendar.JDateChooser dataCalendar;
    private javax.swing.JLabel immagineTestataPazienti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelCellulare;
    private javax.swing.JLabel labelCognome;
    private javax.swing.JLabel labelDataNascita;
    private javax.swing.JLabel labelNome;
    private javax.swing.JList listaCellulari;
    private javax.swing.JButton pAddCellulare;
    private javax.swing.JButton pRemCellulare;
    private javax.swing.JButton pulsanteAggiungi;
    private javax.swing.JButton pulsanteCancella;
    private javax.swing.JButton pulsanteCancellaTutti;
    private javax.swing.JButton pulsanteEsci;
    private javax.swing.JButton pulsanteHome;
    private javax.swing.JButton pulsanteModifica;
    private javax.swing.JButton pulsanteOK;
    private javax.swing.JTable tabellaPazienti;
    private javax.swing.JFormattedTextField txCellularePaziente;
    private javax.swing.JTextField txCognomePaziente;
    private javax.swing.JLabel txErrore;
    private javax.swing.JTextField txModalita;
    private javax.swing.JTextField txNomePaziente;
    private javax.swing.JFormattedTextField txPazienteSelezionato;
    // End of variables declaration                   
	
    //Dichiarazione modello lista cellulari pazienti
    private DefaultListModel<String> modelloListaCellulari;
    private final String modAggiungi = editorPazienti.getString("AGGIUNGI");
    private final String modModifica = editorPazienti.getString("MODIFICA N.");

    @Override
    public void open() {
        start();
    }
   
    private enum Modalita{aggiungi, modifica};
    private Modalita modalita;
    private String txDataNascita = "";
    private int rigaSelezionata = -1;
}
