/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adisys.server.boundary;

import adisys.server.strumenti.ComboItem;
import adisys.server.strumenti.DateFormatConverter;
import adisys.server.strumenti.Record;
import adisys.server.strumenti.VariableTableModel;
import business.infermiere.InfermiereTO;
import integration.dao.InfermiereMySqlDAO;
import messaggistica.GMessage;
import messaggistica.MainException;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import presentation.FrontController;
import presentation.RequestManager;

/**
 *
 * @author Francesco
 */
public class Pianificatore extends javax.swing.JFrame implements Boundary {
    private static ResourceBundle pianificatore = ResourceBundle.getBundle("adisys/server/property/Pianificatore");
    FrontController FC;
    private static final String FORMATO_DATA_INPUT = DateFormatConverter.getFormatData();
    private final Calendar c = Calendar.getInstance();
    private SimpleDateFormat dateFormat = new SimpleDateFormat(FORMATO_DATA_INPUT);
    private final String dataCorrente = dateFormat.format(c.getTime());
    private long currentLongDate = DateFormatConverter.dateString2long(dataCorrente, 
            FORMATO_DATA_INPUT);
    
    public static void setResourceBundle(String path, Locale locale){
        pianificatore = ResourceBundle.getBundle(path, locale);
    }
    
	/**
	 * Creates new form ADISysGUI
	 */
	public Pianificatore() throws MainException {
            initComponents();
            fieldCombo();
            setDate();
            aggiornaTabelle();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        etichettaLogo = new javax.swing.JLabel();
        intestazione = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        labelPazienti = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabellaPazienti = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        labelInfermieri = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellaInfermieri = new javax.swing.JTable();
        labelPatologie = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabellaPatologie = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labelInterventi = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabellaInterventi = new javax.swing.JTable();
        pulsanteIndietro3 = new javax.swing.JButton();
       
        comboInfermieri = new javax.swing.JComboBox();
        txRicDataDal = new com.toedter.calendar.JDateChooser();
        txRicDataAl = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pulsanteResettaRicerca = new javax.swing.JButton();
        pulsanteEsci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        barraDeiMenu = new javax.swing.JMenuBar();
        menuModifica = new javax.swing.JMenu();
        menuAggiungiPaziente = new javax.swing.JMenuItem();
        menuAggiungiInfermiere = new javax.swing.JMenuItem();
        menuAggiungiPatologie = new javax.swing.JMenuItem();
        menuAggiungiIntervento = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuAggiornaTabelle = new javax.swing.JMenuItem();
        menuFile = new javax.swing.JMenu();
        menuEsportazione = new javax.swing.JMenuItem();
        menuVerifica = new javax.swing.JMenu();
        menuVerificaDati = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(pianificatore.getString("ADISYS - PIANIFICAZIONE GIORNALIERA")); // NOI18N
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        etichettaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/decorazioniFinestre/adisyssrvflat.png"))); // NOI18N

        intestazione.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/decorazioniFinestre/Pianificazione.png"))); // NOI18N

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(500, 500));

        jSplitPane2.setBorder(null);
        jSplitPane2.setDividerLocation(380);
        jSplitPane2.setAutoscrolls(true);

        labelPazienti.setFont(labelPazienti.getFont().deriveFont(labelPazienti.getFont().getStyle() | java.awt.Font.BOLD, 14));
        labelPazienti.setForeground(new java.awt.Color(255, 255, 255));
        labelPazienti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPazienti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/barre/Verde.png"))); // NOI18N
        labelPazienti.setText(pianificatore.getString("PAZIENTI")); // NOI18N
        labelPazienti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tabellaPazienti.setAutoCreateRowSorter(true);
        tabellaPazienti.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabellaPazienti.setNextFocusableComponent(tabellaInterventi);
        tabellaPazienti.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaPazienti.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabellaPazienti);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelPazienti)
                .addGap(0, 85, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(labelPazienti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(jPanel3);

        labelInfermieri.setFont(labelInfermieri.getFont().deriveFont(labelInfermieri.getFont().getStyle() | java.awt.Font.BOLD, 14));
        labelInfermieri.setForeground(new java.awt.Color(255, 255, 255));
        labelInfermieri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfermieri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/barre/Rossa.png"))); // NOI18N
        labelInfermieri.setText(pianificatore.getString("INFERMIERI")); // NOI18N
        labelInfermieri.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tabellaInfermieri.setAutoCreateRowSorter(true);
        tabellaInfermieri.setName("Pazienti"); // NOI18N
        tabellaInfermieri.setNextFocusableComponent(tabellaInfermieri);
        tabellaInfermieri.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaInfermieri.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabellaInfermieri);

        labelPatologie.setFont(labelPatologie.getFont().deriveFont(labelPatologie.getFont().getStyle() | java.awt.Font.BOLD, 14));
        labelPatologie.setForeground(new java.awt.Color(255, 255, 255));
        labelPatologie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPatologie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/barre/arancione.png"))); // NOI18N
        labelPatologie.setText(pianificatore.getString("PATOLOGIE")); // NOI18N
        labelPatologie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tabellaPatologie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tabellaPatologie);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInfermieri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelPatologie)
                        .addContainerGap())
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInfermieri)
                    .addComponent(labelPatologie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel2);

        jSplitPane1.setLeftComponent(jSplitPane2);

        labelInterventi.setFont(labelInterventi.getFont().deriveFont(labelInterventi.getFont().getStyle() | java.awt.Font.BOLD, 14));
        labelInterventi.setForeground(new java.awt.Color(255, 255, 255));
        labelInterventi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInterventi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/barre/Azzurra.png"))); // NOI18N
        labelInterventi.setText(pianificatore.getString("INTERVENTI")); // NOI18N
        labelInterventi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tabellaInterventi.setAutoCreateRowSorter(true);
        tabellaInterventi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaInterventi.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabellaInterventi);

        pulsanteIndietro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/indietro.png"))); // NOI18N
        pulsanteIndietro3.setText(pianificatore.getString("TORNA ALL'EDITOR SCELTA")); // NOI18N
        pulsanteIndietro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteIndietro3ActionPerformed(evt);
            }
        });

      

        comboInfermieri.setToolTipText(pianificatore.getString("SELEZIONA L'INFERMIERE PER CUI FILTRARE GLI INTERVENTI")); // NOI18N
        comboInfermieri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInfermieriActionPerformed(evt);
            }
        });

        txRicDataDal.setToolTipText(pianificatore.getString("SELEZIONA UNA DATA PER FILTRARE GLI INTERVENTI")); // NOI18N
        txRicDataDal.setDateFormatString("dd/MM/yyyy");
        txRicDataDal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txRicDataDalPropertyChange(evt);
            }
        });

        txRicDataAl.setToolTipText(pianificatore.getString("SELEZIONA UNA DATA PER FILTRARE GLI INTERVENTI")); // NOI18N
        txRicDataAl.setDateFormatString("dd/MM/yyyy");
        txRicDataAl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txRicDataAlPropertyChange(evt);
            }
        });

        jLabel3.setText(pianificatore.getString("FILTRA INTERVENTI DAL:")); // NOI18N

        jLabel4.setText(pianificatore.getString("AL:")); // NOI18N

        pulsanteResettaRicerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/reset.png"))); // NOI18N
        pulsanteResettaRicerca.setToolTipText(pianificatore.getString("RESETTA I FILTRI DI RICERCA")); // NOI18N
        pulsanteResettaRicerca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteResettaRicerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteResettaRicercaActionPerformed(evt);
            }
        });

        pulsanteEsci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/arresta.png"))); // NOI18N
        pulsanteEsci.setText(pianificatore.getString("ABBANDONA ADISYS")); // NOI18N
        pulsanteEsci.setToolTipText(pianificatore.getString("ESCI DA ADISYS")); // NOI18N
        pulsanteEsci.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEsciActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText(pianificatore.getString("INFO_NUM_INTERVENTI")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pulsanteEsci)
                .addGap(350, 350, 350)
                
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(pulsanteIndietro3))
            .addComponent(jScrollPane3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelInterventi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboInfermieri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txRicDataDal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(txRicDataAl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(122, 122, 122)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addComponent(pulsanteResettaRicerca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 407, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pulsanteResettaRicerca)
                    .addComponent(comboInfermieri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelInterventi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txRicDataDal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txRicDataAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pulsanteEsci))
                    .addComponent(pulsanteIndietro3))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel1);

        barraDeiMenu.setRequestFocusEnabled(false);

        menuModifica.setText(pianificatore.getString("DATI")); // NOI18N

        menuAggiungiPaziente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuAggiungiPaziente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaPazienti.png"))); // NOI18N
        menuAggiungiPaziente.setText(pianificatore.getString("APRI EDITOR PAZIENTI...")); // NOI18N
        menuAggiungiPaziente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAggiungiPazienteActionPerformed(evt);
            }
        });
        menuModifica.add(menuAggiungiPaziente);

        menuAggiungiInfermiere.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        menuAggiungiInfermiere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaInfermieri.png"))); // NOI18N
        menuAggiungiInfermiere.setText(pianificatore.getString("APRI EDITOR INFERMIERI...")); // NOI18N
        menuAggiungiInfermiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAggiungiInfermiereActionPerformed(evt);
            }
        });
        menuModifica.add(menuAggiungiInfermiere);

        menuAggiungiPatologie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuAggiungiPatologie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaPatologie.png"))); // NOI18N
        menuAggiungiPatologie.setText(pianificatore.getString("APRI EDITOR PATOLOGIE...")); // NOI18N
        menuAggiungiPatologie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAggiungiPatologieActionPerformed(evt);
            }
        });
        menuModifica.add(menuAggiungiPatologie);

        menuAggiungiIntervento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuAggiungiIntervento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaInterventi.png"))); // NOI18N
        menuAggiungiIntervento.setText(pianificatore.getString("APRI EDITOR INTERVENTI...")); // NOI18N
        menuAggiungiIntervento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAggiungiInterventoActionPerformed(evt);
            }
        });
        menuModifica.add(menuAggiungiIntervento);
        menuModifica.add(jSeparator1);

        menuAggiornaTabelle.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuAggiornaTabelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaAggiorna.png"))); // NOI18N
        menuAggiornaTabelle.setText(pianificatore.getString("AGGIORNA DATI TABELLE")); // NOI18N
        menuAggiornaTabelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAggiornaTabelleActionPerformed(evt);
            }
        });
        menuModifica.add(menuAggiornaTabelle);

        barraDeiMenu.add(menuModifica);

        menuFile.setText(pianificatore.getString("ESPORTA")); // NOI18N

        menuEsportazione.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuEsportazione.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaEsportazione.png"))); // NOI18N
        menuEsportazione.setText(pianificatore.getString("ESPORTA PIANIFICAZIONE...")); // NOI18N
        menuEsportazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEsportazioneActionPerformed(evt);
            }
        });
        menuFile.add(menuEsportazione);

        barraDeiMenu.add(menuFile);

        menuVerifica.setText(pianificatore.getString("VERIFICA")); // NOI18N

        menuVerificaDati.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuVerificaDati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adisys/server/img/pulsanti/IconaVerifica.png"))); // NOI18N
        menuVerificaDati.setText(pianificatore.getString("VERIFICA DEI DATI")); // NOI18N
        menuVerificaDati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerificaDatiActionPerformed(evt);
            }
        });
        menuVerifica.add(menuVerificaDati);

        barraDeiMenu.add(menuVerifica);

        setJMenuBar(barraDeiMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(intestazione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 653, Short.MAX_VALUE)
                .addComponent(etichettaLogo))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intestazione)
                    .addComponent(etichettaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

	private void menuAggiungiInterventoActionPerformed(java.awt.event.ActionEvent evt) {                                                       
            EditorInterventi.setPianificatore(this);
            request(RequestManager.APRI_EDITOR_INTERVENTI);
	}                                                      

	private void menuAggiungiPazienteActionPerformed(java.awt.event.ActionEvent evt) {                                                     
            request(RequestManager.APRI_EDITOR_PAZIENTI);
	}                                                    

	private void menuAggiungiInfermiereActionPerformed(java.awt.event.ActionEvent evt) {                                                       
            request(RequestManager.APRI_EDITOR_INFERMIERI);
	}                                                      

	private void menuVerificaDatiActionPerformed(java.awt.event.ActionEvent evt) {                                                 
            request(RequestManager.APRI_DIALOGO_VERIFICA);
	}                                                

        private void request(String request){
            FC = RequestManager.getFCInstance();
            if(FC.processRequest(request)){
                System.out.println("Finestra " + request + " aperta con successo.");
            }
            else{
                messaggistica.GMessage.winNotFound(request);
            }
        }
        
	private void menuAggiornaTabelleActionPerformed(java.awt.event.ActionEvent evt) {                                                    
          
            aggiornaTabelle();
            
	}                                                   

	private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
           System.out.println(pianificatore.getString("FINESTRA PIANIFICAZIONE ATTIVATA - TABELLE AGGIORNATE"));
           aggiornaTabelle();
           
	}                                    

    private void menuEsportazioneActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        request(RequestManager.APRI_DIALOGO_ESPORTAZIONE);
    }                                                

    private void menuAggiungiPatologieActionPerformed(java.awt.event.ActionEvent evt) {                                                      
       request(RequestManager.APRI_EDITOR_PATOLOGIE);
    }                                                     

    private void pulsanteIndietro3ActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        this.dispose();
        request(RequestManager.APRI_EDITOR_LANGUAGE);
    }                                                 

    private void pulsanteServerActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.dispose();
        request(RequestManager.APRI_EDITOR_DATABASE);
    }                                              

    private void comboInfermieriActionPerformed(java.awt.event.ActionEvent evt) {                                                
        try {
            ricercaFiltrata();
        } catch (MainException ex) {
            Logger.getLogger(EditorInterventi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                               

    private void txRicDataDalPropertyChange(java.beans.PropertyChangeEvent evt) {                                            
        if(txRicDataDal.getDate() != null)
        try {
            ricercaFiltrata();
        } catch (MainException ex) {
            Logger.getLogger(EditorInterventi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                           

           public void ricercaFiltrata() throws MainException {                                                      
		int id = -1;
                String dataDal = "";
                String dataAl = "";
                if(txRicDataDal.getDate() != null){
                    SimpleDateFormat dateFormat = new SimpleDateFormat(FORMATO_DATA_INPUT);
                    dataDal = dateFormat.format(txRicDataDal.getDate());
                }
                
                if(txRicDataAl.getDate() != null){
                    SimpleDateFormat dateFormat = new SimpleDateFormat(FORMATO_DATA_INPUT);
                    dataAl = dateFormat.format(txRicDataAl.getDate());
                }
			String strId = ((ComboItem) comboInfermieri.getSelectedItem()).getValue();
			
			if(!strId.equals(""))
				id = Integer.parseInt(strId);
                        
                          FC = RequestManager.getFCInstance();
                          ArrayList<Record<String, Object>> params = new ArrayList<>();
                          params.add(new Record<String, Object>("java.lang.Integer", id));
                          params.add(new Record<String, Object>("java.lang.String", dataDal));
                          params.add(new Record<String, Object>("java.lang.String", dataAl));
                          AbstractTableModel modelAdisys = (AbstractTableModel) 
                                  FC.processRequest("visualizzaTabellaInterventiInfermiere", params);
                          tabellaInterventi.setModel(modelAdisys);
                          tabellaInterventi = verificaTabellaPiena(tabellaInterventi, pianificatore.getString("INTERVENTO"));
                        
	} 
           
    private void txRicDataAlPropertyChange(java.beans.PropertyChangeEvent evt) {                                           
        if(txRicDataAl.getDate() != null)
        try {
            ricercaFiltrata();
        } catch (MainException ex) {
            Logger.getLogger(EditorInterventi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                          

    private void pulsanteResettaRicercaActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        comboInfermieri.setSelectedIndex(0);
        txRicDataDal.setDate(null);
        txRicDataAl.setDate(null);
        try {
            ricercaFiltrata();
        } catch (MainException ex) {
            Logger.getLogger(EditorInterventi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                      

    private void pulsanteEsciActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(GMessage.confirm(pianificatore.getString("SEI SICURO DI VOLER ABBANDONARE")
            + pianificatore.getString(" ADISYS?")) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }                                            

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        if(GMessage.confirm(pianificatore.getString("SEI SICURO DI VOLER TORNARE INDIETRO?"))
                == JOptionPane.YES_OPTION) {
        this.dispose();
        request(RequestManager.APRI_EDITOR_LANGUAGE);
        }
    }                                  

    private void fieldCombo() throws MainException{
          
        FC = RequestManager.getFCInstance();
	ArrayList<ComboItem> lista = (ArrayList<ComboItem>) FC.processRequest("visualizzaElenco", null);
        comboInfermieri.addItem(new ComboItem("", pianificatore.getString("FILTRA INTERVENTI PER:")));
        for (ComboItem objA : lista) {
            comboInfermieri.addItem(objA);
        }
      }
      
      private void setDate(){
          txRicDataDal.setDate(new Date(currentLongDate));
          txRicDataAl.setDate(new Date(currentLongDate));
      }
      
      public void setDate(String date){
          long dateInsert = DateFormatConverter.dateString2long(date, FORMATO_DATA_INPUT);
          txRicDataAl.setDate(new Date(dateInsert));
      }
	/**
	 *
	 */
	public static void start() {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if (pianificatore.getString("NIMBUS").equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Pianificatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Pianificatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Pianificatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Pianificatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
                            try {                           
                                Pianificatore window = new Pianificatore();
                                Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit().getScreenSize();
                                window.setLocation(new Point( (risoluzioneSchermo.width - window.getWidth()) /2, (risoluzioneSchermo.height - window.getHeight()) /2)  );
                                window.setVisible(true);
                            } catch (MainException ex) {
                                Logger.getLogger(Pianificatore.class.getName()).log(Level.SEVERE, null, ex);
                            }
                          
			}
		});

	}

   private JTable verificaTabellaPiena(JTable tabella, String label) throws MainException{
             String[] msg = new String[1];
                        msg[0] = java.text.MessageFormat.format(
                                pianificatore.getString("NON È STATO TROVATO ALCUN {0}"), new Object[] {label});
            if(tabella.getRowCount() == 0){
                if(label.equals(pianificatore.getString("INTERVENTO"))){
                        String strId = "";
                        String strName = "";
                        int noInfo = 0;
                        if(tabellaInfermieri.getColumnCount() != 1 && tabella.getRowCount() != 0){
                            strId = ((ComboItem) comboInfermieri.getSelectedItem()).getValue();
                            strName = ((ComboItem) comboInfermieri.getSelectedItem()).getName();
                            noInfo = 1;
                        }
			if(comboInfermieri.getSelectedIndex() != 0 && comboInfermieri.getSelectedIndex() != -1)
                            msg[0] = msg[0] + pianificatore.getString("PER L'INFERMIERE") + 
                                    ((ComboItem) comboInfermieri.getSelectedItem()).getName();
                        if(txRicDataDal.getDate() != null){
                            SimpleDateFormat dateFormat = new SimpleDateFormat(FORMATO_DATA_INPUT);
                            String strDataDal = dateFormat.format(txRicDataDal.getDate());
                            msg[0] = msg[0] + java.text.MessageFormat.format(pianificatore.getString(" DAL {0}"), new Object[] {strDataDal});
                            noInfo = 1;
                        }
                        if(txRicDataAl.getDate() != null){
                            SimpleDateFormat dateFormat = new SimpleDateFormat(FORMATO_DATA_INPUT);
                            String strDataAl = dateFormat.format(txRicDataAl.getDate());
                            msg[0] = msg[0] + java.text.MessageFormat.format(pianificatore.getString(" AL {0}"), new Object[] {strDataAl});
                        } else {
                            if(noInfo == 1){
                                /*SimpleDateFormat dateFormat = new SimpleDateFormat(FORMATO_DATA_INPUT);
                                String strDataDal = dateFormat.format(txRicDataDal.getDate());
                                long dataDal =
                                        DateFormatConverter.dateString2long(strDataDal, FORMATO_DATA_INPUT);
                                if(dataDal - DateFormatConverter)*/
                                msg[0] = msg[0] + pianificatore.getString("AD OGGI");
                            }
                                
                        }
                    }
                VariableTableModel modello = new VariableTableModel();
                msg[0] = msg[0] + pianificatore.getString("REGISTRATO");
                modello.addColumn("");             
                modello.addRow(msg);
                tabella.setModel(modello);
            } else {
                if(label.equals(pianificatore.getString("INFERMIERE"))){
                       
                            TableColumnModel columnModel = tabella.getColumnModel();
                            TableColumn[] column = new TableColumn[columnModel.getColumnCount()];
                            String[] header = new String[columnModel.getColumnCount()];
                            for(int i = 0; i < columnModel.getColumnCount(); i++){
                                column[i] = columnModel.getColumn(i);
                                header[i] = column[i].getHeaderValue().toString();
                            }
                    
                            VariableTableModel newModel = new VariableTableModel();
                            newModel.setColumnIdentifiers(header);
                            
                            for(int i = 0; i < tabella.getRowCount(); i++){
                                newModel.addRow(column);
                                int j;
                                InfermiereTO to = null;
                                for(j = 0; j < tabella.getColumnCount(); j++){
                                    Object value = tabella.getValueAt(i, j);
                                    newModel.setValueAt(value, i, j);
                                    if(j == tabella.getColumn(InfermiereMySqlDAO.NOME_COLONNA_ID)
                                            .getModelIndex()){
                                        to = new InfermiereTO();
                                        to.setID(Integer.parseInt(value.toString()));
                                    }
                                    if(j == tabella.getColumn("NUMINTERVENTI").getModelIndex()){
                                        ArrayList<Record<String, Object>> params = new ArrayList<Record<String, Object>>();
                                         params.add(new Record<String, Object>("business.infermiere.InfermiereTO", to));
                                        int numInt = (int) FC.processRequest("contaInterventi", params);
                                        newModel.setValueAt(numInt, i, j);
                                    }
                                }
                                
                            }
                            tabella.setModel(newModel);
                }
            }
            return tabella;
        }
        
	private void aggiornaTabelle()
	{
        try {
            //AGGIORNAMENTO DELLE TABELLE
            FC = RequestManager.getFCInstance();
            AbstractTableModel modelAdisys = (AbstractTableModel) FC.processRequest("visualizzaInfermieriConInterventi", null);
            tabellaInfermieri.setModel(modelAdisys);
            tabellaInfermieri = verificaTabellaPiena(tabellaInfermieri, pianificatore.getString("INFERMIERE"));

            
            modelAdisys = (AbstractTableModel) FC.processRequest("visualizzaPazienti", null);
            tabellaPazienti.setModel(modelAdisys);
            tabellaPazienti = verificaTabellaPiena(tabellaPazienti, pianificatore.getString("PAZIENTE"));
           
            ricercaFiltrata();
            tabellaInterventi = verificaTabellaPiena(tabellaInterventi, pianificatore.getString("INTERVENTO"));
            
            modelAdisys = (AbstractTableModel) FC.processRequest("visualizzaPatologie", null);
            tabellaPatologie.setModel(modelAdisys);
            tabellaPatologie = verificaTabellaPiena(tabellaPatologie, pianificatore.getString("PATOLOGIA"));
        } catch (MainException ex) {
            Logger.getLogger(Pianificatore.class.getName()).log(Level.SEVERE, null, ex);
        }
                
	}

    // Variables declaration - do not modify                     
    private javax.swing.JMenuBar barraDeiMenu;
    private javax.swing.JComboBox comboInfermieri;
    private javax.swing.JLabel etichettaLogo;
    private javax.swing.JLabel intestazione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel labelInfermieri;
    private javax.swing.JLabel labelInterventi;
    private javax.swing.JLabel labelPatologie;
    private javax.swing.JLabel labelPazienti;
    private javax.swing.JMenuItem menuAggiornaTabelle;
    private javax.swing.JMenuItem menuAggiungiInfermiere;
    private javax.swing.JMenuItem menuAggiungiIntervento;
    private javax.swing.JMenuItem menuAggiungiPatologie;
    private javax.swing.JMenuItem menuAggiungiPaziente;
    private javax.swing.JMenuItem menuEsportazione;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuModifica;
    private javax.swing.JMenu menuVerifica;
    private javax.swing.JMenuItem menuVerificaDati;
    private javax.swing.JButton pulsanteEsci;
    private javax.swing.JButton pulsanteIndietro3;
    private javax.swing.JButton pulsanteResettaRicerca;
   
    private javax.swing.JTable tabellaInfermieri;
    private javax.swing.JTable tabellaInterventi;
    private javax.swing.JTable tabellaPatologie;
    private javax.swing.JTable tabellaPazienti;
    private com.toedter.calendar.JDateChooser txRicDataAl;
    private com.toedter.calendar.JDateChooser txRicDataDal;
    // End of variables declaration                   

    @Override
    public void apri() {
        start();
    }


}
